//! Bidirectional migration mechanism: the `_migrations` metadata
//! table, an owned per-migration applier, and the open logic that lets an older
//! binary open a database written by a newer one.
//!
//! The knowledge an old binary needs to step back down travels *inside* the
//! database. Every applied migration records — in the same transaction as its
//! `up` — its checksum, kind, and stored `down_sql`, so no reachable state ever
//! has a schema change without its antidote. When a binary opens a database
//! whose `user_version` is ahead of its own migration count, it reads those
//! rows and either overlays (all the extra migrations are additive, so the
//! newer schema is safe to run against untouched) or, if any is breaking, runs
//! the stored downs in reverse under a pre-taken file snapshot and verifies the
//! result against its own ground-truth schema before committing.
//!
//! The forward path ([`MigrationSet::to_latest`]) applies each pending
//! migration in its own transaction with foreign keys OFF on the migration
//! connection, counting `user_version` up one per applied migration, and
//! records each migration's metadata row in that same transaction.

use crate::db_error::{DbError, DbResult};
use crate::schema_dump::{dump_schema, executable_statements};
use rusqlite::{Connection, params};
use sha2::{Digest, Sha256};
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::time::Duration;

/// The fresh-install baseline: the committed, normalized schema
/// dump of the full migration chain, generated by `new_migration` every time
/// it produces a new migration. The one file with two consumers: the schema
/// snapshot test byte-compares it as text (`tests/schema_snapshot.rs`), and
/// [`MigrationSet::install_baseline`] replays it as executable DDL
/// ([`executable_statements`]) here.
const BASELINE_DUMP: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/baseline/baseline.sql"
));

/// Literal row data historical migrations write, replayed after `baseline.sql`
/// on a fresh install so the baseline path is behaviorally identical to the
/// chain path — not just schema-identical. `baseline.sql` is a pure schema
/// dump (it is the same normalized `sqlite_master` artifact the
/// schema snapshot test compares) and cannot carry row data by construction,
/// so any migration that seeds a real row rather than transforming existing
/// ones needs its insert repeated here explicitly. Exactly one exists across
/// the 25 historical migrations: `20260223000000_add_servers` seeds a default
/// `ServerGroup` so every install — chain or baseline — starts with one.
const HISTORICAL_SEED_DATA: &[&str] =
    &["INSERT INTO \"ServerGroup\" (\"name\", \"groupIndex\") VALUES ('Default', 0);"];

/// Whether a migration can be safely overlaid by an older binary (`Additive`)
/// or requires a down-run to step back past it (`Breaking`).
///
/// `Additive` means the migration only adds objects an older binary ignores and
/// introduces no constraint capable of rejecting that binary's writes. Kind is
/// derived, not trusted, by the generator; this enum is the
/// runtime carrier.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MigrationKind {
    Additive,
    Breaking,
}

impl MigrationKind {
    /// The `kind` column's stored text form.
    pub fn as_str(self) -> &'static str {
        match self {
            MigrationKind::Additive => "additive",
            MigrationKind::Breaking => "breaking",
        }
    }

    /// Parses the stored `kind` text back into the enum.
    pub fn parse(s: &str) -> Option<MigrationKind> {
        match s {
            "additive" => Some(MigrationKind::Additive),
            "breaking" => Some(MigrationKind::Breaking),
            _ => None,
        }
    }
}

/// One migration's full definition, carried by the binary. Replaces the bare
/// `up` SQL string the runner used to hold: the down script, kind, and
/// lossiness declaration travel alongside so the runner can both apply forward
/// and, for older binaries, step back down.
#[derive(Clone, Copy, Debug)]
pub struct MigrationDef {
    /// The migration directory name (e.g. `20240120134904_init`), stored in the
    /// `name` column.
    pub name: &'static str,
    /// The `up` SQL, applied forward and hashed into the checksum.
    pub up_sql: &'static str,
    /// The stored `down` SQL, executed in reverse when an older binary steps
    /// past this migration. `None` for the historical migrations that predate
    /// the floor and are never down-run.
    pub down_sql: Option<&'static str>,
    /// Whether an older binary may overlay this migration or must down-run it.
    pub kind: MigrationKind,
    /// Lossiness declaration stored in `data_down`: `full`, `partial:<fields>`,
    /// or `none`.
    pub data_down: &'static str,
}

/// The binary's ordered migration list. `version` is the 1-based index into
/// `migrations`; the on-disk `user_version` counts the same sequence.
pub struct MigrationSet {
    pub migrations: Vec<MigrationDef>,
}

/// What the runner decided after inspecting the database, consumed by the
/// bootstrap which turns it into `_STATUS_:` lines. Every fatal outcome is a
/// [`RefusalKind`]; `Proceed` and `Downgraded` continue startup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OpenVerdict {
    /// Startup continues against the existing (possibly overlaid) schema.
    Proceed,
    /// A breaking down-run succeeded and the schema is back at the binary's own
    /// version; startup continues. Bootstrap emits `_STATUS_:DB_DOWNGRADED`.
    Downgraded,
    /// Startup must abort; see [`RefusalKind`].
    Refuse(RefusalKind),
}

/// Why the runner refused to proceed. Each maps to a distinct fatal status.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RefusalKind {
    /// `user_version` is ahead but the metadata to step back is missing — a
    /// pre-floor database an old binary cannot understand. Today's behavior.
    BackwardsMigration,
    /// A recorded migration's checksum disagrees with this binary's for the same
    /// version: divergent history (e.g. a stable hotfix vs a different beta at
    /// the same number). Never assume; refuse.
    Diverged { version: i32 },
    /// A breaking down-run could not restore the binary's own schema. The
    /// database is left untouched (rolled back).
    ///
    /// `snapshot_path` carries the pre-downgrade snapshot only when restoring it
    /// would actually change the database. The down-run is atomic, so the usual
    /// outcome is that the rollback already left the file in the state a restore
    /// would produce; offering one then would loop the recovery screen forever
    /// on its own recommended action.
    DowngradeFailed { snapshot_path: Option<PathBuf> },
}

const CREATE_MIGRATIONS_TABLE: &str = "CREATE TABLE IF NOT EXISTS _migrations (\
    version INTEGER PRIMARY KEY, \
    name TEXT NOT NULL, \
    checksum TEXT NOT NULL, \
    kind TEXT NOT NULL, \
    down_sql TEXT, \
    data_down TEXT NOT NULL DEFAULT 'full', \
    applied_at INTEGER NOT NULL)";

const MIGRATION_ROW_COLUMNS: &str = "_migrations (version, name, checksum, kind, down_sql, data_down, applied_at) \
    VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)";

impl MigrationSet {
    /// The number of migrations this binary carries — the `user_version` a
    /// fully-upgraded database reaches.
    pub fn count(&self) -> i32 {
        self.migrations.len() as i32
    }

    /// sha256 (hex) of a migration's `up` SQL. Detects a divergent history at
    /// the same version number.
    pub fn checksum(&self, version: i32) -> String {
        sha256_hex(self.migrations[(version - 1) as usize].up_sql.as_bytes())
    }

    /// Forward-only application, used by tests and tooling that always start at
    /// or below the binary's version. Ensures the metadata table exists,
    /// backfills rows for migrations already applied to the schema, then applies
    /// every pending migration — each `up` plus its `_migrations` row plus the
    /// `user_version` bump in one transaction.
    pub fn to_latest(&self, conn: &mut Connection) -> DbResult<()> {
        ensure_migrations_table(conn)?;
        // Table redefinitions in the historical migrations require FKs OFF on
        // the migration connection.
        conn.pragma_update(None, "foreign_keys", "OFF")?;
        let count = self.count();
        let user_version = read_user_version(conn)?;
        self.backfill_applied(conn, user_version.min(count))?;
        self.apply_pending(conn, user_version, count)?;
        Ok(())
    }

    /// The production open path. Returns the verdict the bootstrap
    /// turns into a status line.
    ///
    /// - Truly fresh install (empty `sqlite_master`): execute the
    ///   committed baseline instead of replaying the chain, `Proceed`.
    /// - `user_version <= count`: backfill + apply pending forward, `Proceed`.
    /// - `user_version > count`, all extra migrations additive: overlay,
    ///   touching nothing, `Proceed`.
    /// - `user_version > count`, any extra breaking: snapshot, run the stored
    ///   downs in reverse in one verified transaction, `Downgraded` on success
    ///   or `Refuse(DowngradeFailed)` with the snapshot preserved.
    /// - metadata missing above `count`: `Refuse(BackwardsMigration)`.
    /// - a recorded checksum disagrees at or below `count`: `Refuse(Diverged)`.
    pub fn open(&self, conn: &mut Connection, db_path: &Path) -> DbResult<OpenVerdict> {
        // Distinct from the legacy `user_version = 0`-with-tables case, which
        // still carries the `_prisma_migrations` shim: a truly empty
        // `sqlite_master` has never been touched by any binary, so the whole
        // chain can be replaced by one vetted baseline. This check
        // must run before `ensure_migrations_table` creates a row of its own.
        if sqlite_master_is_empty(conn)? {
            return self.install_baseline(conn);
        }

        ensure_migrations_table(conn)?;
        conn.pragma_update(None, "foreign_keys", "OFF")?;

        let count = self.count();
        let user_version = read_user_version(conn)?;

        // Divergence is checked before anything else: a forked history at a
        // known version taints the whole database, up or down.
        // CENSUS-RULE: compat.diverged-checksum
        if let Some(version) = self.first_divergent(conn, user_version.min(count))? {
            return Ok(OpenVerdict::Refuse(RefusalKind::Diverged { version }));
        }

        if user_version > count {
            return self.handle_ahead(conn, db_path, count, user_version);
        }

        self.backfill_applied(conn, user_version)?;
        self.apply_pending(conn, user_version, count)?;
        Ok(OpenVerdict::Proceed)
    }

    /// Records `_migrations` rows for migrations `1..=upto` that are already
    /// applied to the schema but lack a metadata row — the first-run backfill
    /// for a database upgraded by a pre-floor binary. Idempotent via
    /// `INSERT OR IGNORE`.
    fn backfill_applied(&self, conn: &Connection, upto: i32) -> DbResult<()> {
        for version in 1..=upto {
            let def = &self.migrations[(version - 1) as usize];
            conn.execute(
                &format!("INSERT OR IGNORE INTO {MIGRATION_ROW_COLUMNS}"),
                params![
                    version,
                    def.name,
                    self.checksum(version),
                    def.kind.as_str(),
                    def.down_sql,
                    def.data_down,
                    now_millis(),
                ],
            )?;
        }
        Ok(())
    }

    /// Applies migrations `from+1..=to`, each in its own transaction: `up`, the
    /// `_migrations` row, and the `user_version` bump commit together so no
    /// reachable state carries a schema change without its metadata.
    ///
    /// The metadata row is `INSERT OR REPLACE`d rather than plain-inserted: a
    /// file-level restore (e.g. a Time Machine / VSS snapshot of just the main
    /// database file, taken out of sync with its `-wal`) can leave a stale
    /// `_migrations` row for a version above the restored `user_version` — a
    /// row from history this restore rolled back past. A plain `INSERT` would
    /// then hit that row's `version` primary key and fail with a constraint
    /// violation the moment this loop reaches it, rolling back an otherwise
    /// perfectly applicable migration and turning a self-healable state into a
    /// fatal `DB_MIGRATION_FAILED`. `REPLACE` instead overwrites the stale row
    /// with the metadata for the `up` this transaction is applying right now —
    /// exactly what belongs at that version — which is a no-op in the
    /// overwhelmingly common case where no such row exists yet.
    fn apply_pending(&self, conn: &mut Connection, from: i32, to: i32) -> DbResult<()> {
        for version in (from + 1)..=to {
            let def = &self.migrations[(version - 1) as usize];
            let tx = conn.transaction()?;
            tx.execute_batch(def.up_sql)?;
            tx.execute(
                &format!("INSERT OR REPLACE INTO {MIGRATION_ROW_COLUMNS}"),
                params![
                    version,
                    def.name,
                    self.checksum(version),
                    def.kind.as_str(),
                    def.down_sql,
                    def.data_down,
                    now_millis(),
                ],
            )?;
            tx.pragma_update(None, "user_version", version)?;
            tx.commit()?;
        }
        Ok(())
    }

    /// Returns the lowest version `1..=upto` whose recorded checksum disagrees
    /// with this binary's, or `None` if every recorded row matches.
    fn first_divergent(&self, conn: &Connection, upto: i32) -> DbResult<Option<i32>> {
        if upto < 1 {
            return Ok(None);
        }
        let mut stmt = conn.prepare(
            "SELECT version, checksum FROM _migrations WHERE version BETWEEN 1 AND ?1 ORDER BY version",
        )?;
        let rows = stmt.query_map([upto], |row| {
            Ok((row.get::<_, i32>(0)?, row.get::<_, String>(1)?))
        })?;
        for row in rows {
            let (version, stored) = row?;
            if (version as usize) <= self.migrations.len() && self.checksum(version) != stored {
                return Ok(Some(version));
            }
        }
        Ok(None)
    }

    /// `user_version > count`: decide overlay vs down-run vs backwards refusal.
    fn handle_ahead(
        &self,
        conn: &mut Connection,
        db_path: &Path,
        count: i32,
        user_version: i32,
    ) -> DbResult<OpenVerdict> {
        // Rows for every version ahead of our own, newest first (down-run order).
        //
        // Bounded above by `user_version`, which counts what was actually
        // applied. A torn file-level restore (a VSS or Time Machine copy of the
        // main file out of sync with its -wal) can leave `_migrations` rows for
        // versions the restored schema never received; `apply_pending` was
        // hardened for that same state. Down-running such a row would apply a
        // migration's inverse to a schema that never got its forward half, and
        // for the hand-written DML class of down that transforms data while
        // leaving the schema untouched — so the verification below still
        // matches and the corruption commits as a successful downgrade.
        let stale_ahead = {
            let mut stmt = conn.prepare(
                "SELECT version FROM _migrations WHERE version > ?1 ORDER BY version DESC",
            )?;
            let rows = stmt.query_map([user_version], |row| row.get::<_, i32>(0))?;
            rows.collect::<Result<Vec<_>, _>>()?
        };
        if !stale_ahead.is_empty() {
            tracing::warn!(
                "ignoring _migrations row(s) {stale_ahead:?} above user_version {user_version}: \
                 recorded but never applied to this schema, so their downs are not run"
            );
        }

        let ahead = {
            let mut stmt = conn.prepare(
                "SELECT version, kind, down_sql FROM _migrations
                 WHERE version > ?1 AND version <= ?2
                 ORDER BY version DESC",
            )?;
            let rows = stmt.query_map([count, user_version], |row| {
                Ok((
                    row.get::<_, i32>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, Option<String>>(2)?,
                ))
            })?;
            rows.collect::<Result<Vec<_>, _>>()?
        };

        // Any version in (count, user_version] without a metadata row is a
        // pre-floor database we cannot step back through.
        let present: HashSet<i32> = ahead.iter().map(|(v, _, _)| *v).collect();
        // CENSUS-RULE: compat.backwards-missing-metadata
        if ((count + 1)..=user_version).any(|v| !present.contains(&v)) {
            return Ok(OpenVerdict::Refuse(RefusalKind::BackwardsMigration));
        }

        if ahead
            .iter()
            .all(|(_, kind, _)| MigrationKind::parse(kind) == Some(MigrationKind::Additive))
        {
            tracing::info!(
                "overlay: {} additive migration(s) ahead of own count {}; running against the newer schema untouched",
                ahead.len(),
                count
            );
            return Ok(OpenVerdict::Proceed);
        }

        self.down_run(conn, db_path, count, &ahead)
    }

    /// Runs the stored downs for `ahead` (newest first) under a pre-taken file
    /// snapshot, in one transaction, and verifies the result equals this
    /// binary's own schema at `count` before committing. Any failure rolls back
    /// and preserves the snapshot.
    fn down_run(
        &self,
        conn: &mut Connection,
        db_path: &Path,
        count: i32,
        ahead: &[(i32, String, Option<String>)],
    ) -> DbResult<OpenVerdict> {
        // Snapshot the file BEFORE any destructive step. Checkpoint first so the
        // -wal contents are folded into the main file the copy captures. A busy
        // checkpoint is not treated as good enough: see
        // `checkpoint_before_snapshot` for why.
        checkpoint_before_snapshot(conn)?;
        let snapshot_path = snapshot_path_for(db_path);
        std::fs::copy(db_path, &snapshot_path)
            .map_err(|e| DbError::Conversion(format!("pre-downgrade snapshot copy failed: {e}")))?;

        let reference = self.reference_schema(count)?;

        let tx = conn.transaction()?;
        for (version, _kind, down_sql) in ahead {
            // CENSUS-RULE: compat.downgrade-breaking-no-down
            let Some(sql) = down_sql else {
                // A breaking migration ahead with no stored down cannot be
                // reversed; refuse and keep the snapshot.
                tracing::error!(
                    "down-run refused: migration {version} is breaking but has no stored down"
                );
                drop(tx);
                return Ok(OpenVerdict::Refuse(RefusalKind::DowngradeFailed {
                    snapshot_path: snapshot_if_restorable(db_path, snapshot_path),
                }));
            };
            // CENSUS-RULE: compat.downgrade-corrupt-down
            if let Err(e) = tx.execute_batch(sql) {
                tracing::error!("down-run of migration {version} failed: {e}");
                drop(tx); // rollback: the whole down-run is atomic
                return Ok(OpenVerdict::Refuse(RefusalKind::DowngradeFailed {
                    snapshot_path: snapshot_if_restorable(db_path, snapshot_path),
                }));
            }
            tx.execute(
                "DELETE FROM _migrations WHERE version = ?1",
                params![version],
            )?;
        }
        tx.pragma_update(None, "user_version", count)?;

        // Verify against our own ground truth before committing: the future's
        // downs are trusted, then checked.
        // CENSUS-RULE: compat.downgrade-schema-mismatch
        let actual = dump_schema(&tx)?;
        if actual == reference {
            tx.commit()?;
            Ok(OpenVerdict::Downgraded)
        } else {
            tracing::error!(
                "down-run verification failed: resulting schema does not match this build's schema at version {count}"
            );
            drop(tx); // rollback: never leave a half-downgraded schema
            Ok(OpenVerdict::Refuse(RefusalKind::DowngradeFailed {
                snapshot_path: snapshot_if_restorable(db_path, snapshot_path),
            }))
        }
    }

    /// Fresh-install path: executes the committed baseline in one
    /// transaction instead of replaying the historical chain, then backfills
    /// full `_migrations` metadata — downs included, straight from the binary,
    /// exactly as the chain path's `to_latest` would leave it — and sets
    /// `user_version` to this binary's count. One transaction start to finish:
    /// any failure leaves the untouched empty database behind, never a
    /// half-created schema.
    fn install_baseline(&self, conn: &mut Connection) -> DbResult<OpenVerdict> {
        let count = self.count();
        // `foreign_keys` is a per-connection runtime flag, not a schema
        // property: SQLite makes it a no-op to change once a transaction is
        // open, so it must be set on the raw connection before `transaction()`
        // starts one (matching `to_latest`/`open`).
        conn.pragma_update(None, "foreign_keys", "OFF")?;
        let tx = conn.transaction()?;

        let statements = executable_statements(BASELINE_DUMP);
        tx.execute_batch(&statements.join("\n"))?;
        for seed in HISTORICAL_SEED_DATA {
            tx.execute_batch(seed)?;
        }

        tx.execute_batch(CREATE_MIGRATIONS_TABLE)?;
        self.backfill_applied(&tx, count)?;
        tx.pragma_update(None, "user_version", count)?;

        tx.commit()?;
        tracing::info!(
            "fresh install: executed baseline.sql ({count} migrations) instead of replaying the chain"
        );
        Ok(OpenVerdict::Proceed)
    }

    /// Builds this binary's pristine schema at `version` in memory by applying
    /// its own ups `1..=version`, then dumps it through the shared normalizer —
    /// the ground truth a down-run result must match.
    fn reference_schema(&self, version: i32) -> DbResult<String> {
        let conn = Connection::open_in_memory()?;
        conn.pragma_update(None, "foreign_keys", "OFF")?;
        for v in 1..=version {
            conn.execute_batch(self.migrations[(v - 1) as usize].up_sql)?;
        }
        dump_schema(&conn)
    }
}

/// sha256 (hex) of `bytes` — the exact hash [`MigrationSet::checksum`] applies
/// to a migration's `up_sql`. Exposed so tooling that must compute a
/// migration's checksum before `get_migrations()` carries it — `new_migration`
/// freezing it into `tests/migration_checksums_frozen.rs` — uses the identical
/// algorithm rather than a hand-copied one.
pub fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex::encode(hasher.finalize())
}

/// Creates the `_migrations` bookkeeping table if it does not already exist.
fn ensure_migrations_table(conn: &Connection) -> DbResult<()> {
    conn.execute_batch(CREATE_MIGRATIONS_TABLE)?;
    Ok(())
}

/// Reads `PRAGMA user_version`, defaulting to 0.
fn read_user_version(conn: &Connection) -> DbResult<i32> {
    Ok(conn.pragma_query_value(None, "user_version", |row| row.get(0))?)
}

/// True when `sqlite_master` has no rows at all: a database no binary, old or
/// new, has ever touched. Distinct from `user_version = 0` with tables already
/// present (the legacy `_prisma_migrations` case), which is not this branch.
fn sqlite_master_is_empty(conn: &Connection) -> DbResult<bool> {
    let count: i64 = conn.query_row("SELECT COUNT(*) FROM sqlite_master", [], |row| row.get(0))?;
    Ok(count == 0)
}

/// How many times [`checkpoint_before_snapshot`] retries a busy `wal_checkpoint`
/// before giving up.
const CHECKPOINT_BUSY_RETRIES: u32 = 3;

/// The delay between retries. Three retries at this spacing (750ms total) is
/// long enough to ride out ordinary, short-lived contention — a reader that is
/// mid-commit or about to close its transaction — without turning a
/// merely-slow checkpoint into a false refusal, while staying short enough
/// that a genuinely stuck checkpoint (a long-lived open read transaction
/// elsewhere in the app) fails fast instead of stalling startup for seconds.
/// `wal_checkpoint`'s own `busy` result already distinguishes "blocked" from
/// "slow", so there is no reason to wait longer than it takes to find out
/// whether the contention is transient.
const CHECKPOINT_BUSY_RETRY_DELAY: Duration = Duration::from_millis(250);

/// Runs `PRAGMA wal_checkpoint(TRUNCATE)` and inspects its result instead of
/// discarding it. SQLite returns `(busy, log, checkpointed)`: `busy != 0` means
/// the checkpoint could not fully run — typically another connection holds a
/// read snapshot the TRUNCATE step cannot invalidate — and the frames from the
/// last session's writes can be left behind in the `-wal` file rather than
/// folded into the main database file. The caller copies the main file
/// immediately after this call to make the pre-downgrade snapshot: the ONLY
/// recovery artifact a failed downgrade leaves behind. A discarded `busy`
/// result would let that copy silently miss committed data while still
/// reporting a clean snapshot, which is worse than refusing outright — a
/// refused downgrade can be retried, but a stale snapshot looks trustworthy
/// and is not.
///
/// Retries up to [`CHECKPOINT_BUSY_RETRIES`] times, sleeping
/// [`CHECKPOINT_BUSY_RETRY_DELAY`] between attempts, before returning `Err`.
///
/// `conn`'s busy_timeout is saved and forced to zero for the span of this
/// call, then restored. Left at its normal (rusqlite defaults every
/// connection to 5 seconds) value, a single contended `wal_checkpoint` call
/// would have SQLite's own busy handler silently retry *inside* that one
/// call for the full timeout before ever reporting `busy` back to us —
/// stacking underneath this function's own retry loop and turning an
/// intended ~750ms refusal into one that can take tens of seconds. With it
/// forced to zero, each attempt reports its result immediately and
/// [`CHECKPOINT_BUSY_RETRY_DELAY`] is the only backoff actually in effect.
// CENSUS-RULE: compat.downgrade-checkpoint-busy
fn checkpoint_before_snapshot(conn: &Connection) -> DbResult<()> {
    let prior_timeout_ms: i64 = conn.pragma_query_value(None, "busy_timeout", |row| row.get(0))?;
    conn.busy_timeout(Duration::ZERO)?;
    let result = checkpoint_with_retries(conn);
    // Best-effort restore: the checkpoint's own outcome is what matters, and
    // this pragma has no real failure mode short of the connection already
    // being unusable, in which case `result` above already carries the error.
    let _ = conn.busy_timeout(Duration::from_millis(prior_timeout_ms.max(0) as u64));
    result
}

/// The retry loop itself, run with `conn`'s busy_timeout already forced to
/// zero by [`checkpoint_before_snapshot`] so each `wal_checkpoint` attempt
/// below returns immediately rather than silently blocking inside SQLite's
/// own busy handler.
fn checkpoint_with_retries(conn: &Connection) -> DbResult<()> {
    for attempt in 0..=CHECKPOINT_BUSY_RETRIES {
        let (busy, _log, _checkpointed): (i64, i64, i64) =
            conn.query_row("PRAGMA wal_checkpoint(TRUNCATE)", [], |row| {
                Ok((row.get(0)?, row.get(1)?, row.get(2)?))
            })?;
        if busy == 0 {
            return Ok(());
        }
        if attempt < CHECKPOINT_BUSY_RETRIES {
            std::thread::sleep(CHECKPOINT_BUSY_RETRY_DELAY);
        }
    }
    Err(DbError::Conversion(format!(
        "wal_checkpoint(TRUNCATE) still busy after {CHECKPOINT_BUSY_RETRIES} retries; refusing \
         to take a pre-downgrade snapshot that could silently miss frames still in the -wal file"
    )))
}

/// Decides whether the snapshot taken before a down-run is worth offering.
///
/// The down-run runs in one transaction, so a failure rolls the database back to
/// exactly the bytes the snapshot holds. Restoring it would then be a no-op, and
/// because the recovery screen presents restore as its recommended action the
/// user would loop on it until taking the rung that deletes the database. The
/// snapshot is only reported when it actually differs, and is removed otherwise
/// so no stale copy accumulates beside the database.
fn snapshot_if_restorable(db_path: &Path, snapshot_path: PathBuf) -> Option<PathBuf> {
    let differs = match (std::fs::read(db_path), std::fs::read(&snapshot_path)) {
        (Ok(db), Ok(snap)) => db != snap,
        // Unreadable either side: keep the snapshot rather than discard the only
        // copy of data we cannot compare.
        _ => true,
    };

    if differs {
        return Some(snapshot_path);
    }

    if let Err(e) = std::fs::remove_file(&snapshot_path) {
        tracing::warn!(
            "could not remove the redundant pre-downgrade snapshot at {}: {e}",
            snapshot_path.display()
        );
    }
    None
}

/// The pre-downgrade snapshot path beside the database file: `<stem>.pre-downgrade.db`
/// (so the runtime `gdl_conf.db` yields `gdl_conf.pre-downgrade.db`).
fn snapshot_path_for(db_path: &Path) -> PathBuf {
    let stem = db_path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("gdl_conf");
    db_path.with_file_name(format!("{stem}.pre-downgrade.db"))
}

/// Current unix time in milliseconds — the storage unit for `applied_at`, matching
/// every other datetime column.
fn now_millis() -> i64 {
    chrono::Utc::now().timestamp_millis()
}
