type Theme = {
  // Colors
  accent: string;
  primary: string;
  "primary-hover": string;
  "darkSlate-50": string;
  "darkSlate-100": string;
  "darkSlate-200": string;
  "darkSlate-300": string;
  "darkSlate-400": string;
  "darkSlate-500": string;
  "darkSlate-600": string;
  "darkSlate-700": string;
  "darkSlate-800": string;
  "darkSlate-900": string;
  "lightSlate-50": string;
  "lightSlate-100": string;
  "lightSlate-200": string;
  "lightSlate-300": string;
  "lightSlate-400": string;
  "lightSlate-500": string;
  "lightSlate-600": string;
  "lightSlate-700": string;
  "lightSlate-800": string;
  "lightSlate-900": string;
  "darkGray-50": string;
  "darkGray-100": string;
  "darkGray-200": string;
  "darkGray-300": string;
  "darkGray-400": string;
  "darkGray-500": string;
  "darkGray-600": string;
  "darkGray-700": string;
  "darkGray-800": string;
  "darkGray-900": string;
  "lightGray-50": string;
  "lightGray-100": string;
  "lightGray-200": string;
  "lightGray-300": string;
  "lightGray-400": string;
  "lightGray-500": string;
  "lightGray-600": string;
  "lightGray-700": string;
  "lightGray-800": string;
  "lightGray-900": string;
  "blue-50": string;
  "blue-100": string;
  "blue-200": string;
  "blue-300": string;
  "blue-400": string;
  "blue-500": string;
  "blue-600": string;
  "blue-700": string;
  "blue-800": string;
  "blue-900": string;
  red: string;
  "red-hover": string;
  yellow: string;
  "yellow-hover": string;
};

export type { Theme };
export { mainTheme } from "./main";
export { lightTheme } from "./light";
export { poisonGreen } from "./poison-green";
