[package]
name = "carbon_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.147", features = ["derive", "rc"] }
anyhow = "1.0.51"
tokio = { version = "1.22.0", features = ["full"] }
rspc = { version = "0.1.2", features = ["axum"] }
async-stream = "0.3.3"
tower-http = { version = "0.3.4", default-features = false, features = ["cors"] }
axum = { version = "0.5.17", features = ["ws"] }
