use std::collections::HashMap;

use anyhow::bail;
use serde::{Deserialize, Serialize};

mod scan;
mod v1;

pub use scan::scan_dir;

#[derive(Debug)]
pub struct PackInfo {
    pub files: HashMap<String, FileHashes>,
}

#[derive(Debug, Clone)]
pub struct FileHashes {
    pub sha512: [u8; 64],
    pub md5: [u8; 16],
}

#[derive(Serialize, Deserialize)]
#[serde(tag = "_version")]
enum PackInfoWrapper {
    #[serde(rename = "1")]
    V1(v1::PackInfo),
}

pub fn parse_packinfo(packinfo_str: &str) -> anyhow::Result<PackInfo> {
    let packinfo = serde_json::from_str::<PackInfoWrapper>(packinfo_str)?;

    let packinfo = match packinfo {
        PackInfoWrapper::V1(packinfo) => packinfo.into(),
    };

    validate_packinfo(&packinfo)?;

    Ok(packinfo)
}

/// packinfo.json is generated by GDLauncher itself and never hand-edited, so
/// any key that fails this is corruption, not a normal input to tolerate —
/// fail loud here rather than let a malformed key reach a later
/// `data_path.join(...)` (see the join-replaces-base hazard documented on
/// [`super::super::normalize_cleanup_path`], whose validation this keeps
/// consistent with).
fn validate_packinfo(packinfo: &PackInfo) -> anyhow::Result<()> {
    for key in packinfo.files.keys() {
        validate_packinfo_key(key)?;
    }
    Ok(())
}

/// A valid packinfo key: starts with `/`, names something after it (len >
/// 1), contains no doubled `/` (a `//` leaves an absolute-looking tail once
/// the single leading `/` is stripped for joining onto a data dir — and
/// `Path::join` with an absolute argument replaces the base entirely, so
/// that tail would escape it), no `\` (a Windows drive/UNC smuggle vector),
/// and no bare `..` path segment.
fn validate_packinfo_key(key: &str) -> anyhow::Result<()> {
    // Display (`{key}`), not Debug (`{key:?}`): Debug escapes a backslash as
    // `\\`, which would make the offending key's own error message no
    // longer contain the literal key.
    if !key.starts_with('/') || key.len() <= 1 {
        bail!("packinfo key '{key}' must start with '/' and name a non-empty path");
    }
    if key.contains("//") {
        bail!("packinfo key '{key}' contains a doubled '/'");
    }
    if key.contains('\\') {
        bail!("packinfo key '{key}' contains a backslash");
    }
    if has_dotdot_segment(key) {
        bail!("packinfo key '{key}' contains a '..' path segment");
    }
    Ok(())
}

/// True if `path` contains a bare `..` path segment — an exact segment
/// match, never merely a `..` substring within a longer segment such as
/// `foo..bar.jar`.
///
/// Shared by `validate_packinfo_key` (parse-time rejection) and the
/// join-site containment guards in `disk_scan.rs` and `run/modpack.rs`:
/// `Path::starts_with` alone does not catch a `..` escape, because it
/// compares path *components* lexically without ever resolving `..` —
/// `data_path.join("mods/../../evil").starts_with(data_path)` is `true`
/// even though the resolved path escapes `data_path` entirely. Those join
/// sites re-run this exact check themselves, immediately before joining,
/// rather than trusting that `parse_packinfo` already ran — the same
/// segment-exact test, extracted once so both call sites can never drift
/// from what the parser itself rejects.
pub fn has_dotdot_segment(path: &str) -> bool {
    path.split('/').any(|segment| segment == "..")
}

pub fn make_packinfo(info: PackInfo) -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(&PackInfoWrapper::V1(info.into()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn packinfo_with_key(key: &str) -> PackInfo {
        let mut files = HashMap::new();
        files.insert(
            key.to_string(),
            FileHashes {
                sha512: [0u8; 64],
                md5: [0u8; 16],
            },
        );
        PackInfo { files }
    }

    /// Round-trips through the real (unvalidated) serializer so these tests
    /// exercise `parse_packinfo` against JSON exactly as it would actually be
    /// produced by a corrupted `packinfo.json`, rather than a hand-typed
    /// literal that might not match the wire format.
    fn serialize(key: &str) -> String {
        make_packinfo(packinfo_with_key(key)).unwrap()
    }

    #[test]
    fn parse_packinfo_rejects_empty_key() {
        let err = parse_packinfo(&serialize("")).unwrap_err();
        assert!(
            err.to_string().contains("''"),
            "error should name the offending key: {err}"
        );
    }

    #[test]
    fn parse_packinfo_rejects_double_slash_key() {
        let err = parse_packinfo(&serialize("//tmp/x")).unwrap_err();
        assert!(
            err.to_string().contains("//tmp/x"),
            "error should name the offending key: {err}"
        );
    }

    #[test]
    fn parse_packinfo_rejects_backslash_and_dotdot() {
        let err = parse_packinfo(&serialize("/mods/..\\evil.jar")).unwrap_err();
        assert!(
            err.to_string().contains("/mods/..\\evil.jar"),
            "error should name the offending key: {err}"
        );

        let err = parse_packinfo(&serialize("/mods/../evil.jar")).unwrap_err();
        assert!(
            err.to_string().contains("/mods/../evil.jar"),
            "error should name the offending key: {err}"
        );
    }

    #[test]
    fn parse_packinfo_accepts_a_well_formed_key() {
        let packinfo = parse_packinfo(&serialize("/mods/a.jar")).unwrap();
        assert!(packinfo.files.contains_key("/mods/a.jar"));
    }
}
