project_id: "530210"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_url: "https://api.crowdin.com"
commit_message: "[skip ci] new translations %language% - %original_file_name% from Crowdin"
append_commit_message: false
preserve_hierarchy: true
files:
  - source: "/packages/i18n/locale/english/*.json"
    ignore:
      - LICENSE
    translation: "/packages/i18n/locale/%language%/%original_file_name%"
    type: json
