project_id: '530216'
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ./packages/i18n
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /en/*.json
    ignore:
      - LICENSE
    translation: '%two_letters_code%/%original_file_name%'
    type: json
