#!/usr/bin/env node

/**
 * Translation Type Generator
 *
 * Generates TypeScript type definitions for all translation keys
 * to provide type-safe translation key usage with autocomplete.
 *
 * Usage:
 *   node scripts/generateTranslationTypes.mjs
 */

import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const LOCALE_DIR = path.resolve(
  __dirname,
  "../../../packages/i18n/locale/english"
)
const OUTPUT_FILE = path.resolve(
  __dirname,
  "../../../packages/i18n/src/keys.generated.ts"
)

/**
 * Get all JSON files in the locale directory (excluding special files)
 */
async function getNamespaceFiles() {
  const files = await fs.readdir(LOCALE_DIR)
  return files
    .filter((f) => f.endsWith(".json"))
    .filter((f) => !f.includes(".backup"))
    .map((f) => f.replace(".json", ""))
}

/**
 * Read and parse a namespace file
 */
async function readNamespace(namespace) {
  const filePath = path.join(LOCALE_DIR, `${namespace}.json`)
  const content = await fs.readFile(filePath, "utf-8")
  return JSON.parse(content)
}

/**
 * Escape string for use in TypeScript string literal
 */
function escapeKey(key) {
  // Always quote keys to avoid TS syntax errors (dots, underscores, etc.)
  return `"${key.replace(/"/g, '\\"')}"`
}

/**
 * Detect i18next plural suffixes (_zero, _one, _two, _few, _many, _other)
 * and add the base key so t("key", { count }) works with TypeScript types.
 */
function addPluralBaseKeys(keys) {
  const pluralSuffixes = ["_zero", "_one", "_two", "_few", "_many", "_other"]
  const baseKeys = new Set()

  for (const key of keys) {
    for (const suffix of pluralSuffixes) {
      if (key.endsWith(suffix)) {
        baseKeys.add(key.slice(0, -suffix.length))
        break
      }
    }
  }

  // Add base keys that aren't already present
  const keySet = new Set(keys)
  for (const base of baseKeys) {
    if (!keySet.has(base)) {
      keys.push(base)
    }
  }

  return keys
}

/**
 * Generate TypeScript type for a namespace's keys
 */
function generateNamespaceType(namespace, keys) {
  const typeName =
    namespace.charAt(0).toUpperCase() + namespace.slice(1) + "Keys"
  const allKeys = addPluralBaseKeys([...keys])
  const keyList = allKeys.map(escapeKey).join(" | ")

  return `export type ${typeName} = ${keyList ? keyList : "never"};`
}

/**
 * Generate the complete TypeScript file
 */
async function generateTypes() {
  console.log("🎨 Generating TypeScript translation types...\n")

  const namespaces = await getNamespaceFiles()
  console.log(`📂 Found ${namespaces.length} namespaces\n`)

  const typeDefs = []
  const namespaceTypes = []

  // Generate type for each namespace
  for (const namespace of namespaces.sort()) {
    const translations = await readNamespace(namespace)
    const keys = Object.keys(translations)

    console.log(`   ${namespace}: ${keys.length} keys`)

    const typeName =
      namespace.charAt(0).toUpperCase() + namespace.slice(1) + "Keys"
    typeDefs.push(generateNamespaceType(namespace, keys))
    namespaceTypes.push(typeName)
  }

  // Generate union type of all keys
  const allKeysType = `export type TranslationKey = ${namespaceTypes.join(" | ")};`

  // Generate namespaced key type (with "namespace:key" format)
  const namespacedKeyParts = namespaces.map((ns) => {
    const typeName = ns.charAt(0).toUpperCase() + ns.slice(1) + "Keys"
    return `  | \`${ns}:\${${typeName}}\``
  })

  const namespacedKeyType = `export type NamespacedTranslationKey =\n${namespacedKeyParts.join("\n")}\n  | TranslationKey; // Keys without prefix use default namespace`

  // Generate the file header
  const header = `/**
 * Auto-generated translation key types
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Generated by: scripts/generateTranslationTypes.mjs
 * Generated at: ${new Date().toISOString()}
 *
 * This file provides type-safe translation keys for the i18n system.
 * Use these types with the Trans component to get autocomplete and type checking.
 */

/* eslint-disable */

`

  // Combine everything
  const content = [
    header,
    "// Individual namespace key types",
    ...typeDefs,
    "",
    "// Union of all translation keys",
    allKeysType,
    "",
    '// Namespaced keys (e.g., "auth:login.welcome_to")',
    namespacedKeyType,
    ""
  ].join("\n")

  // Write to file
  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true })
  await fs.writeFile(OUTPUT_FILE, content, "utf-8")

  console.log(`\n✅ Types generated successfully!`)
  console.log(`📄 Output: ${OUTPUT_FILE}`)
  console.log(`📊 Total keys: ${namespaceTypes.length * 2} types`)
}

// Run generator
generateTypes().catch((error) => {
  console.error("❌ Type generation failed:", error)
  process.exit(1)
})
