/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function fibonacci(num: number, num1: number): Promise<number>
export function computePathMurmur(path: string): Promise<number>
export function auth(): Promise<void>
