//! Build script for auto-discovering migrations at compile time.
//!
//! This script scans the `migrations/` folder and generates Rust code
//! that embeds all migration SQL files, sorted by timestamp.

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let migrations_dir = Path::new(&manifest_dir).join("migrations");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("migrations_generated.rs");

    // Collect migration directories (filter out non-directories and other files)
    let mut migrations: Vec<String> = fs::read_dir(&migrations_dir)
        .expect("Failed to read migrations directory")
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.is_dir() {
                let name = entry.file_name().to_string_lossy().to_string();
                // Verify migration.sql exists
                if path.join("migration.sql").exists() {
                    Some(name)
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    // Sort by timestamp prefix (lexicographic works for YYYYMMDDHHMMSS format)
    migrations.sort();

    // Generate the Rust code
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs - DO NOT EDIT\n\n");
    code.push_str("use rusqlite_migration::{Migrations, M};\n\n");

    code.push_str(&format!(
        "/// Total number of migrations (auto-generated).\n"
    ));
    code.push_str(&format!(
        "pub const MIGRATION_COUNT: i32 = {};\n\n",
        migrations.len()
    ));

    code.push_str("/// Load all migrations from embedded SQL files (auto-generated).\n");
    code.push_str("pub fn get_migrations() -> Migrations<'static> {\n");
    code.push_str("    Migrations::new(vec![\n");

    for name in &migrations {
        code.push_str(&format!(
            "        M::up(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/migrations/{}/migration.sql\"))),\n",
            name
        ));
    }

    code.push_str("    ])\n");
    code.push_str("}\n");

    // Write the generated file
    let mut file = fs::File::create(&dest_path).expect("Failed to create generated file");
    file.write_all(code.as_bytes())
        .expect("Failed to write generated file");

    // Tell Cargo to rerun if migrations folder changes
    println!("cargo:rerun-if-changed=migrations");
}
