[package]
name = "carbon_repos"
version = "0.1.0"
edition = "2024"

[dependencies]
carbon_macro = { path = "../carbon_macro" }
serde = { workspace = true, features = ["derive", "rc"] }
rusqlite = { version = "0.40.1", features = ["bundled", "hooks", "column_metadata"] }
rusqlite_migration = "2.6.0"
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
