/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface account {
  id: string
  name: string
}
export interface accounts {
  accounts: Array<account>
  selectedAccount?: account
}
export function initAccounts(): Promise<accounts>
export function fibonacci(num: number, num1: number): Promise<number>
export function computePathMurmur(path: string): Promise<number>
export function auth(reporter: (token: string) => void): Promise<string>
