/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface account {
  id: string
  name: string
  accessToken: string
}
export interface accounts {
  accounts: Array<account>
  selectedAccount?: account
}
export interface DeviceCodeObject {
  userCode: string
  link: string
  expiresAt: number
}
export function auth(reporter: (deviceData: DeviceCodeObject) => void): Promise<Account>
export function initAccounts(): Promise<accounts>
export function fibonacci(num: number, num1: number): Promise<number>
export function computePathMurmur(path: string): Promise<number>
