index|ActiveDownloads_file_id_key|ActiveDownloads|CREATE UNIQUE INDEX "ActiveDownloads_file_id_key" ON "ActiveDownloads" ( "file_id" )
index|AppConfiguration_id_key|AppConfiguration|CREATE UNIQUE INDEX "AppConfiguration_id_key" ON "AppConfiguration" ( "id" )
index|CurseForgeModCache_projectId_fileId_key|CurseForgeModCache|CREATE UNIQUE INDEX "CurseForgeModCache_projectId_fileId_key" ON "CurseForgeModCache" ( "projectId" , "fileId" )
index|Instance_shortpath_key|Instance|CREATE UNIQUE INDEX "Instance_shortpath_key" ON "Instance" ( "shortpath" )
index|Java_id_key|Java|CREATE UNIQUE INDEX "Java_id_key" ON "Java" ( "id" )
index|Java_path_key|Java|CREATE UNIQUE INDEX "Java_path_key" ON "Java" ( "path" )
index|ModFileCache_instanceId_filename_key|ModFileCache|CREATE UNIQUE INDEX "ModFileCache_instanceId_filename_key" ON "ModFileCache" ( "instanceId" , "filename" )
index|ModrinthModCache_projectId_versionId_key|ModrinthModCache|CREATE UNIQUE INDEX "ModrinthModCache_projectId_versionId_key" ON "ModrinthModCache" ( "projectId" , "versionId" )
index|ServerModFileCache_serverId_filename_key|ServerModFileCache|CREATE UNIQUE INDEX "ServerModFileCache_serverId_filename_key" ON "ServerModFileCache" ( "serverId" , "filename" )
index|Server_shortpath_key|Server|CREATE UNIQUE INDEX "Server_shortpath_key" ON "Server" ( "shortpath" )
index|sqlite_autoindex_Account_1|Account|
index|sqlite_autoindex_ActiveDownloads_1|ActiveDownloads|
index|sqlite_autoindex_AssetsMetaCache_1|AssetsMetaCache|
index|sqlite_autoindex_CurseForgeModCache_1|CurseForgeModCache|
index|sqlite_autoindex_CurseForgeModImageCache_1|CurseForgeModImageCache|
index|sqlite_autoindex_CurseForgeModpackCache_1|CurseForgeModpackCache|
index|sqlite_autoindex_CurseForgeModpackImageCache_1|CurseForgeModpackImageCache|
index|sqlite_autoindex_FrontendPreference_1|FrontendPreference|
index|sqlite_autoindex_HTTPCache_1|HTTPCache|
index|sqlite_autoindex_JavaProfile_1|JavaProfile|
index|sqlite_autoindex_Java_1|Java|
index|sqlite_autoindex_LocalModImageCache_1|LocalModImageCache|
index|sqlite_autoindex_LwjglMetaCache_1|LwjglMetaCache|
index|sqlite_autoindex_ModFileCache_1|ModFileCache|
index|sqlite_autoindex_ModMetadata_1|ModMetadata|
index|sqlite_autoindex_ModrinthModCache_1|ModrinthModCache|
index|sqlite_autoindex_ModrinthModImageCache_1|ModrinthModImageCache|
index|sqlite_autoindex_ModrinthModpackCache_1|ModrinthModpackCache|
index|sqlite_autoindex_ModrinthModpackImageCache_1|ModrinthModpackImageCache|
index|sqlite_autoindex_PartialVersionInfoCache_1|PartialVersionInfoCache|
index|sqlite_autoindex_ServerModFileCache_1|ServerModFileCache|
index|sqlite_autoindex_Skin_1|Skin|
index|sqlite_autoindex_VersionInfoCache_1|VersionInfoCache|
table|Account|Account|CREATE TABLE "Account" ( "uuid" TEXT NOT NULL PRIMARY KEY , "username" TEXT NOT NULL , "accessToken" TEXT , "tokenExpires" DATETIME , "msRefreshToken" TEXT , "idToken" TEXT , "lastUsed" DATETIME NOT NULL , "skinId" TEXT , "gdlToken" TEXT )
table|ActiveDownloads|ActiveDownloads|CREATE TABLE "ActiveDownloads" ( "url" TEXT NOT NULL PRIMARY KEY , "file_id" TEXT NOT NULL )
table|AppConfiguration|AppConfiguration|CREATE TABLE "AppConfiguration" ( "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 0 , "theme" TEXT NOT NULL DEFAULT 'main' , "reducedMotion" BOOLEAN NOT NULL DEFAULT false , "language" TEXT NOT NULL DEFAULT 'english' , "discordIntegration" BOOLEAN NOT NULL DEFAULT true , "releaseChannel" TEXT NOT NULL , "activeAccountUuid" TEXT , "concurrentDownloads" INTEGER NOT NULL DEFAULT 10 , "downloadDependencies" BOOLEAN NOT NULL DEFAULT true , "instancesTileSize" INTEGER NOT NULL DEFAULT 2 , "instancesGroupBy" TEXT , "instancesGroupByAsc" BOOLEAN NOT NULL DEFAULT true , "instancesSortBy" TEXT , "instancesSortByAsc" BOOLEAN NOT NULL DEFAULT false , "instancesDuplicateFavorites" BOOLEAN NOT NULL DEFAULT true , "showFeatured" BOOLEAN NOT NULL DEFAULT true , "deletionThroughRecycleBin" BOOLEAN NOT NULL DEFAULT true , "gameResolution" TEXT , "launcherActionOnGameLaunch" TEXT NOT NULL DEFAULT 'none' , "showAppCloseWarning" BOOLEAN NOT NULL DEFAULT true , "javaCustomArgs" TEXT NOT NULL DEFAULT '' , "xmx" INTEGER NOT NULL , "xms" INTEGER NOT NULL DEFAULT 1024 , "defaultInstanceGroup" INTEGER , "preLaunchHook" TEXT , "wrapperCommand" TEXT , "postExitHook" TEXT , "autoManageJavaSystemProfiles" BOOLEAN NOT NULL DEFAULT true , "modPlatformBlacklist" TEXT NOT NULL DEFAULT '' , "modChannels" TEXT NOT NULL DEFAULT 'stable:true , beta:true , alpha:true' , "termsAndPrivacyAccepted" BOOLEAN NOT NULL DEFAULT false , "termsAndPrivacyAcceptedChecksum" TEXT , "gdlAccountUuid" TEXT , "gdlAccountStatus" BLOB , "installationId" TEXT , "serversTileSize" INTEGER NOT NULL DEFAULT 2 , "serversGroupBy" TEXT , "serversGroupByAsc" BOOLEAN NOT NULL DEFAULT true , "serversSortBy" TEXT , "serversSortByAsc" BOOLEAN NOT NULL DEFAULT false , "serversDuplicateFavorites" BOOLEAN NOT NULL DEFAULT true , "defaultServerGroup" INTEGER , CONSTRAINT "AppConfiguration_activeAccountUuid_fkey" FOREIGN KEY ( "activeAccountUuid" ) REFERENCES "Account" ( "uuid" ) ON DELETE SET NULL ON UPDATE CASCADE )
table|AssetsMetaCache|AssetsMetaCache|CREATE TABLE "AssetsMetaCache" ( "id" TEXT NOT NULL PRIMARY KEY , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "assetsIndex" BLOB NOT NULL )
table|CurseForgeModCache|CurseForgeModCache|CREATE TABLE "CurseForgeModCache" ( "metadataId" TEXT NOT NULL PRIMARY KEY , "murmur2" INTEGER NOT NULL , "projectId" INTEGER NOT NULL , "fileId" INTEGER NOT NULL , "name" TEXT NOT NULL , "version" TEXT NOT NULL , "urlslug" TEXT NOT NULL , "summary" TEXT NOT NULL , "authors" TEXT NOT NULL , "releaseType" INTEGER NOT NULL , "updatePaths" TEXT NOT NULL , "cachedAt" DATETIME NOT NULL , CONSTRAINT "CurseForgeModCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "ModMetadata" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|CurseForgeModImageCache|CurseForgeModImageCache|CREATE TABLE "CurseForgeModImageCache" ( "metadataId" TEXT NOT NULL PRIMARY KEY , "url" TEXT NOT NULL , "data" BLOB , "upToDate" INTEGER NOT NULL DEFAULT 0 , CONSTRAINT "CurseForgeModImageCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "CurseForgeModCache" ( "metadataId" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|CurseForgeModpackCache|CurseForgeModpackCache|CREATE TABLE "CurseForgeModpackCache" ( "projectId" INTEGER NOT NULL , "fileId" INTEGER NOT NULL , "modpackName" TEXT NOT NULL , "versionName" TEXT NOT NULL , "urlSlug" TEXT NOT NULL , "updatedAt" DATETIME NOT NULL , PRIMARY KEY ( "projectId" , "fileId" ) )
table|CurseForgeModpackImageCache|CurseForgeModpackImageCache|CREATE TABLE "CurseForgeModpackImageCache" ( "projectId" INTEGER NOT NULL , "fileId" INTEGER NOT NULL , "url" TEXT NOT NULL , "data" BLOB , PRIMARY KEY ( "projectId" , "fileId" ) , CONSTRAINT "CurseForgeModpackImageCache_projectId_fileId_fkey" FOREIGN KEY ( "projectId" , "fileId" ) REFERENCES "CurseForgeModpackCache" ( "projectId" , "fileId" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|FrontendPreference|FrontendPreference|CREATE TABLE "FrontendPreference" ( "key" TEXT NOT NULL PRIMARY KEY , "value" TEXT NOT NULL , "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP )
table|HTTPCache|HTTPCache|CREATE TABLE "HTTPCache" ( "url" TEXT NOT NULL PRIMARY KEY , "status_code" INTEGER NOT NULL , "data" BLOB NOT NULL , "expiresAt" DATETIME DEFAULT CURRENT_TIMESTAMP , "lastModified" TEXT , "etag" TEXT )
table|Instance|Instance|CREATE TABLE "Instance" ( "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT , "name" TEXT NOT NULL , "shortpath" TEXT NOT NULL , "favorite" BOOLEAN NOT NULL DEFAULT false , "hasPackUpdate" BOOLEAN NOT NULL DEFAULT false , "index" INTEGER NOT NULL , "groupId" INTEGER NOT NULL , "libraryPosition" INTEGER , CONSTRAINT "Instance_groupId_fkey" FOREIGN KEY ( "groupId" ) REFERENCES "InstanceGroup" ( "id" ) ON DELETE RESTRICT ON UPDATE CASCADE )
table|InstanceGroup|InstanceGroup|CREATE TABLE "InstanceGroup" ( "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT , "name" TEXT NOT NULL , "groupIndex" INTEGER NOT NULL , "libraryPosition" INTEGER )
table|Java|Java|CREATE TABLE "Java" ( "id" TEXT NOT NULL PRIMARY KEY , "path" TEXT NOT NULL , "major" INTEGER NOT NULL , "fullVersion" TEXT NOT NULL , "type" TEXT NOT NULL , "os" TEXT NOT NULL , "arch" TEXT NOT NULL , "vendor" TEXT NOT NULL , "isValid" BOOLEAN NOT NULL DEFAULT true )
table|JavaProfile|JavaProfile|CREATE TABLE "JavaProfile" ( "name" TEXT NOT NULL PRIMARY KEY , "isSystemProfile" BOOLEAN NOT NULL DEFAULT false , "javaId" TEXT , CONSTRAINT "JavaProfile_javaId_fkey" FOREIGN KEY ( "javaId" ) REFERENCES "Java" ( "id" ) ON DELETE SET NULL ON UPDATE CASCADE )
table|LocalModImageCache|LocalModImageCache|CREATE TABLE "LocalModImageCache" ( "metadataId" TEXT NOT NULL PRIMARY KEY , "data" BLOB NOT NULL , CONSTRAINT "LocalModImageCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "ModMetadata" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|LwjglMetaCache|LwjglMetaCache|CREATE TABLE "LwjglMetaCache" ( "id" TEXT NOT NULL PRIMARY KEY , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "lwjgl" BLOB NOT NULL )
table|ModFileCache|ModFileCache|CREATE TABLE "ModFileCache" ( "id" TEXT NOT NULL PRIMARY KEY , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "instanceId" INTEGER NOT NULL , "filename" TEXT NOT NULL , "filesize" INTEGER NOT NULL , "enabled" BOOLEAN NOT NULL , "addonType" TEXT NOT NULL DEFAULT 'mods' , "metadataId" TEXT NOT NULL , CONSTRAINT "ModFileCache_instanceId_fkey" FOREIGN KEY ( "instanceId" ) REFERENCES "Instance" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE , CONSTRAINT "ModFileCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "ModMetadata" ( "id" ) ON DELETE RESTRICT ON UPDATE CASCADE )
table|ModMetadata|ModMetadata|CREATE TABLE "ModMetadata" ( "id" TEXT NOT NULL PRIMARY KEY , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "murmur2" INTEGER NOT NULL , "sha512" BLOB NOT NULL , "sha1" BLOB NOT NULL , "name" TEXT , "modid" TEXT , "version" TEXT , "description" TEXT , "authors" TEXT , "modloaders" TEXT NOT NULL )
table|ModrinthModCache|ModrinthModCache|CREATE TABLE "ModrinthModCache" ( "metadataId" TEXT NOT NULL PRIMARY KEY , "sha512" TEXT NOT NULL , "projectId" TEXT NOT NULL , "versionId" TEXT NOT NULL , "title" TEXT NOT NULL , "version" TEXT NOT NULL , "urlslug" TEXT NOT NULL , "description" TEXT NOT NULL , "authors" TEXT NOT NULL , "releaseType" INTEGER NOT NULL , "updatePaths" TEXT NOT NULL , "filename" TEXT NOT NULL , "fileUrl" TEXT NOT NULL , "cachedAt" DATETIME NOT NULL , CONSTRAINT "ModrinthModCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "ModMetadata" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|ModrinthModImageCache|ModrinthModImageCache|CREATE TABLE "ModrinthModImageCache" ( "metadataId" TEXT NOT NULL PRIMARY KEY , "url" TEXT NOT NULL , "data" BLOB , "upToDate" INTEGER NOT NULL DEFAULT 0 , CONSTRAINT "ModrinthModImageCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "ModrinthModCache" ( "metadataId" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|ModrinthModpackCache|ModrinthModpackCache|CREATE TABLE "ModrinthModpackCache" ( "projectId" TEXT NOT NULL , "versionId" TEXT NOT NULL , "modpackName" TEXT NOT NULL , "versionName" TEXT NOT NULL , "urlSlug" TEXT NOT NULL , "updatedAt" DATETIME NOT NULL , PRIMARY KEY ( "projectId" , "versionId" ) )
table|ModrinthModpackImageCache|ModrinthModpackImageCache|CREATE TABLE "ModrinthModpackImageCache" ( "projectId" TEXT NOT NULL , "versionId" TEXT NOT NULL , "url" TEXT NOT NULL , "data" BLOB , PRIMARY KEY ( "projectId" , "versionId" ) , CONSTRAINT "ModrinthModpackImageCache_projectId_versionId_fkey" FOREIGN KEY ( "projectId" , "versionId" ) REFERENCES "ModrinthModpackCache" ( "projectId" , "versionId" ) ON DELETE CASCADE ON UPDATE CASCADE )
table|PartialVersionInfoCache|PartialVersionInfoCache|CREATE TABLE "PartialVersionInfoCache" ( "id" TEXT NOT NULL PRIMARY KEY , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "partialVersionInfo" BLOB NOT NULL )
table|Server|Server|CREATE TABLE "Server" ( "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT , "name" TEXT NOT NULL , "shortpath" TEXT NOT NULL , "favorite" BOOLEAN NOT NULL DEFAULT false , "index" INTEGER NOT NULL , "libraryPosition" INTEGER , "groupId" INTEGER NOT NULL , "serverType" TEXT NOT NULL DEFAULT 'vanilla' , "gameVersion" TEXT NOT NULL , "port" INTEGER NOT NULL DEFAULT 25565 , "motd" TEXT NOT NULL DEFAULT 'A Minecraft Server' , "maxPlayers" INTEGER NOT NULL DEFAULT 20 , "onlineMode" BOOLEAN NOT NULL DEFAULT true , "xmx" INTEGER NOT NULL DEFAULT 2048 , "xms" INTEGER NOT NULL DEFAULT 1024 , "extraJavaArgs" TEXT NOT NULL DEFAULT '' , "autoRestart" BOOLEAN NOT NULL DEFAULT false , "dateCreated" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "lastStarted" DATETIME , "providerType" TEXT NOT NULL DEFAULT 'local' , "hostedServerId" TEXT , "iconRevision" INTEGER , "modloaderType" TEXT , "modloaderVersion" TEXT , "modpackPlatform" TEXT , "modpackProjectId" TEXT , "modpackFileId" TEXT , CONSTRAINT "Server_groupId_fkey" FOREIGN KEY ( "groupId" ) REFERENCES "ServerGroup" ( "id" ) ON DELETE RESTRICT ON UPDATE CASCADE )
table|ServerGroup|ServerGroup|CREATE TABLE "ServerGroup" ( "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT , "name" TEXT NOT NULL , "groupIndex" INTEGER NOT NULL , "libraryPosition" INTEGER )
table|ServerModFileCache|ServerModFileCache|CREATE TABLE "ServerModFileCache" ( "id" TEXT NOT NULL PRIMARY KEY DEFAULT ( hex ( randomblob ( 16 ) ) ) , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "serverId" INTEGER NOT NULL , "filename" TEXT NOT NULL , "filesize" INTEGER NOT NULL , "enabled" BOOLEAN NOT NULL DEFAULT 1 , "addonType" TEXT NOT NULL DEFAULT 'mods' , "metadataId" TEXT NOT NULL , CONSTRAINT "ServerModFileCache_serverId_fkey" FOREIGN KEY ( "serverId" ) REFERENCES "Server" ( "id" ) ON DELETE CASCADE ON UPDATE CASCADE , CONSTRAINT "ServerModFileCache_metadataId_fkey" FOREIGN KEY ( "metadataId" ) REFERENCES "ModMetadata" ( "id" ) ON DELETE RESTRICT ON UPDATE CASCADE )
table|Skin|Skin|CREATE TABLE "Skin" ( "id" TEXT NOT NULL PRIMARY KEY , "skin" BLOB NOT NULL )
table|VersionInfoCache|VersionInfoCache|CREATE TABLE "VersionInfoCache" ( "id" TEXT NOT NULL PRIMARY KEY , "lastUpdatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , "versionInfo" BLOB NOT NULL )
table|sqlite_sequence|sqlite_sequence|CREATE TABLE sqlite_sequence ( name , seq )
