import {
  Button,
  toast,
  Input,
  Select,
  SelectTrigger,
  SelectContent,
  SelectItem,
  SelectValue,
  Badge,
  PRESS_CLASSES
} from "@gd/ui"
import { ModalProps, useModal } from "../.."
import { Trans, useTransContext } from "@gd/i18n"
import {
  createEffect,
  createMemo,
  createSignal,
  For,
  Match,
  Show,
  Switch
} from "solid-js"
import { port, rspc } from "@/utils/rspcClient"
import {
  CFFEModLoaderType,
  FEModdedManifestLoaderVersion,
  ManifestVersion,
  McType,
  ModLoader
} from "@gd/core_module/bindings"
import { blobToBase64 } from "@/utils/helpers"
import { useGDNavigate } from "@/managers/NavigationManager"
import ImagePicker from "@/components/ImagePicker"
import { ReactiveMap } from "@solid-primitives/map"
import { useGlobalStore } from "@/components/GlobalStoreContext"
import { getModloaderIcon } from "@/utils/sidebar"

type MappedMcVersions = ManifestVersion & { hasModloader?: boolean }

interface Instancetype {
  id: string
  modloader: CFFEModLoaderType | undefined
  title: string | undefined
  mcVersion: string | undefined
  modloaderVersion: string | undefined
  img: string | undefined
}

enum Modloaders {
  _Quilt = "quilt",
  _Forge = "forge",
  _NeoForge = "neoforge",
  _Fabric = "fabric"
}

const Custom = (props: Pick<ModalProps, "data">) => {
  const [t] = useTransContext()
  const [mappedMcVersions, setMappedMcVersions] = createSignal<
    MappedMcVersions[]
  >([])

  const instanceData = () => props.data as Instancetype | undefined

  const [error, setError] = createSignal("")
  const [bgPreview, setBgPreview] = createSignal<string | null>(
    instanceData()?.img || null
  )
  const [loader, setLoader] = createSignal<CFFEModLoaderType | undefined>(
    instanceData()?.modloader || undefined
  )
  const [loaderVersions, setLoaderVersions] = createSignal<
    FEModdedManifestLoaderVersion[]
  >([])
  const [chosenLoaderVersion, setChosenLoaderVersion] = createSignal(
    instanceData()?.modloaderVersion || undefined
  )
  const [mcVersion, setMcVersion] = createSignal(
    instanceData()?.mcVersion || ""
  )
  const [customTitle, setCustomTitle] = createSignal<string | null>(null)
  const [snapshotVersionFilter, setSnapshotVersionFilter] = createSignal(false)
  const [oldBetaVersionFilter, setOldBetaVersionFilter] = createSignal(false)
  const [oldAlphaVersionFilter, setOldAlphaVersionFilter] = createSignal(false)

  const autoGeneratedName = () =>
    `${loader() || "Vanilla"} ${mcVersion() || mappedMcVersions()?.[0]?.id}`

  const title = createMemo(() => {
    if (customTitle() !== null) return customTitle()
    if (instanceData()?.title) return instanceData()?.title

    return autoGeneratedName()
  })

  const forgeHashmap = new ReactiveMap()
  const neoForgeHashmap = new ReactiveMap()
  const fabricHashmap = new ReactiveMap()
  const quiltHashmap = new ReactiveMap()

  const modalsContext = useModal()
  const globalStore = useGlobalStore()
  const navigator = useGDNavigate()

  const forgeVersionsQuery = rspc.createQuery(() => ({
    queryKey: ["mc.getForgeVersions"],
    enabled: false
  }))

  createEffect(() => {
    if (forgeVersionsQuery.isFetched) {
      forgeVersionsQuery.data?.gameVersions.forEach((version) => {
        forgeHashmap.set(version.id, version.loaders)
      })
    }
  })

  const neoForgeVersionsQuery = rspc.createQuery(() => ({
    queryKey: ["mc.getNeoforgeVersions"],
    enabled: false
  }))

  createEffect(() => {
    if (neoForgeVersionsQuery.isFetched) {
      neoForgeVersionsQuery.data?.gameVersions.forEach((version) => {
        neoForgeHashmap.set(version.id, version.loaders)
      })
    }
  })

  const fabricVersionsQuery = rspc.createQuery(() => ({
    queryKey: ["mc.getFabricVersions"],
    enabled: false
  }))

  createEffect(() => {
    if (fabricVersionsQuery.isFetched) {
      fabricVersionsQuery.data?.gameVersions.forEach((version) => {
        fabricHashmap.set(version.id, version.loaders)
      })
    }
  })

  const quiltVersionsQuery = rspc.createQuery(() => ({
    queryKey: ["mc.getQuiltVersions"],
    enabled: false
  }))

  createEffect(() => {
    if (quiltVersionsQuery.isFetched) {
      quiltVersionsQuery.data?.gameVersions.forEach((version) => {
        quiltHashmap.set(version.id, version.loaders)
      })
    }
  })

  const DUMMY_META_VERSION = "${gdlauncher.gameVersion}"

  const isNeoForge = () => loader() === Modloaders._NeoForge
  const isFabric = () => loader() === Modloaders._Fabric
  const isForge = () => loader() === Modloaders._Forge
  const isQuilt = () => loader() === Modloaders._Quilt

  createEffect(() => {
    if (forgeVersionsQuery.data && isForge()) {
      const versions = forgeVersionsQuery?.data?.gameVersions.find(
        (v) => v.id === (mcVersion() || mappedMcVersions()?.[0]?.id)
      )?.loaders

      setLoaderVersions(versions || [])
      if (instanceData()?.modloader !== "forge") {
        setChosenLoaderVersion(versions?.[0]?.id)
      } else if (
        instanceData()?.modloader === "forge" &&
        instanceData()?.modloaderVersion
      ) {
        setChosenLoaderVersion(instanceData()?.modloaderVersion)
      }
    } else {
      setLoaderVersions([])
    }
  })

  createEffect(() => {
    if (neoForgeVersionsQuery.data && isNeoForge()) {
      const versions = neoForgeVersionsQuery?.data?.gameVersions.find(
        (v) => v.id === (mcVersion() || mappedMcVersions()?.[0]?.id)
      )?.loaders

      setLoaderVersions(versions || [])

      if (instanceData()?.modloader !== "neoforge") {
        setChosenLoaderVersion(versions?.[0]?.id)
      } else if (
        instanceData()?.modloader === "neoforge" &&
        instanceData()?.modloaderVersion
      ) {
        setChosenLoaderVersion(instanceData()?.modloaderVersion)
      }
    } else if (!loader()) {
      setLoaderVersions([])
    }
  })

  createEffect(() => {
    if (fabricVersionsQuery.data && isFabric()) {
      const supported =
        fabricVersionsQuery?.data?.gameVersions.find(
          (v) => v.id === (mcVersion() || mappedMcVersions()?.[0]?.id)
        ) ?? false

      const versions =
        supported !== false
          ? fabricVersionsQuery?.data?.gameVersions.find(
              (v) => v.id === DUMMY_META_VERSION
            )?.loaders
          : []

      setLoaderVersions(versions || [])

      if (instanceData()?.modloader !== "fabric") {
        setChosenLoaderVersion(versions?.[0]?.id)
      } else if (
        instanceData()?.modloader === "fabric" &&
        instanceData()?.modloaderVersion
      ) {
        setChosenLoaderVersion(instanceData()?.modloaderVersion)
      }
    } else if (!loader()) {
      setLoaderVersions([])
    }
  })

  createEffect(() => {
    if (quiltVersionsQuery.data && isQuilt()) {
      const supported =
        quiltVersionsQuery?.data?.gameVersions.find(
          (v) => v.id === (mcVersion() || mappedMcVersions()?.[0]?.id)
        ) ?? false

      const versions =
        supported !== false
          ? quiltVersionsQuery?.data?.gameVersions.find(
              (v) => v.id === DUMMY_META_VERSION
            )?.loaders
          : []

      setLoaderVersions(versions || [])

      if (instanceData()?.modloader !== "quilt") {
        setChosenLoaderVersion(versions?.[0]?.id)
      } else if (
        instanceData()?.modloader === "quilt" &&
        instanceData()?.modloaderVersion
      ) {
        setChosenLoaderVersion(instanceData()?.modloaderVersion)
      }
    } else if (!loader()) {
      setLoaderVersions([])
    }
  })

  createEffect(() => {
    if (!globalStore.minecraftVersions.data) return

    const filteredData = globalStore.minecraftVersions.data.filter(
      (item) =>
        item.type === "release" ||
        (item.type === "snapshot" && snapshotVersionFilter()) ||
        (item.type === "old_beta" && oldBetaVersionFilter()) ||
        (item.type === "old_alpha" && oldAlphaVersionFilter())
    )

    const neoForgeMappedVersions = filteredData.map((item) => {
      return { ...item, hasModloader: neoForgeHashmap.has(item.id) }
    })
    const forgeMappedVersions = filteredData.map((item) => {
      return { ...item, hasModloader: forgeHashmap.has(item.id) }
    })
    const fabricMappedVersions = filteredData.map((item) => {
      return { ...item, hasModloader: fabricHashmap.has(item.id) }
    })
    const quiltMappedVersions = filteredData.map((item) => {
      return { ...item, hasModloader: quiltHashmap.has(item.id) }
    })

    if (isForge()) setMappedMcVersions(forgeMappedVersions)
    else if (isNeoForge()) setMappedMcVersions(neoForgeMappedVersions)
    else if (isFabric()) setMappedMcVersions(fabricMappedVersions)
    else if (isQuilt()) setMappedMcVersions(quiltMappedVersions)
    else setMappedMcVersions(filteredData)

    if (!mcVersion() || !mappedMcVersions().find((v) => v.id === mcVersion())) {
      setMcVersion(mappedMcVersions()[0].id)
    }
  })

  const modloaders: {
    label: string
    key: CFFEModLoaderType | undefined
  }[] = [
    { label: t("instances:_trn_vanilla"), key: undefined },
    { label: t("instances:_trn_forge"), key: "forge" },
    { label: t("instances:_trn_neoforge"), key: "neoforge" },
    { label: t("instances:_trn_fabric"), key: "fabric" },
    { label: t("instances:_trn_quilt"), key: "quilt" }
  ]

  const defaultGroup = rspc.createQuery(() => ({
    queryKey: ["instance.getDefaultGroup"]
  }))

  const prepareInstanceMutation = rspc.createMutation(() => ({
    mutationKey: ["instance.prepareInstance"]
  }))

  const createInstanceMutation = rspc.createMutation(() => ({
    mutationKey: ["instance.createInstance"]
  }))

  const updateInstanceMutation = rspc.createMutation(() => ({
    mutationKey: ["instance.updateInstance"]
  }))

  const mapTypeToColor = (
    type: McType,
    hasNoModloader: boolean | undefined
  ) => {
    return (
      <Switch>
        <Match when={type === "release"}>
          <span
            class="text-green-400"
            classList={{ "opacity-50": hasNoModloader }}
          >{`[${type}]`}</span>
        </Match>
        <Match when={type === "snapshot"}>
          <span
            class="text-yellow-400"
            classList={{ "opacity-50": hasNoModloader }}
          >{`[${type}]`}</span>
        </Match>
        <Match when={type === "old_alpha"}>
          <span
            class="text-purple-400"
            classList={{ "opacity-50": hasNoModloader }}
          >{`[${type}]`}</span>
        </Match>
        <Match when={type === "old_beta"}>
          <span
            class="text-red-400"
            classList={{ "opacity-50": hasNoModloader }}
          >{`[${type}]`}</span>
        </Match>
      </Switch>
    )
  }

  const [iconPath, setIconPath] = createSignal<string | null>(null)

  // Load preview without side effects - just for display
  const loadPreview = async (filePath: string) => {
    const response = await fetch(
      `http://127.0.0.1:${port}/loadImage?path=${encodeURIComponent(filePath)}`
    )
    const blob = await response.blob()
    const b64 = (await blobToBase64(blob)) as string
    setBgPreview(`data:image/png;base64,${b64.substring(b64.indexOf(",") + 1)}`)
    setIconPath(filePath)
  }

  // Store icon in backend before create/update
  const storeIconForBackend = async () => {
    const path = iconPath()
    if (path) {
      const response = await fetch(
        `http://127.0.0.1:${port}/instance/loadIcon?path=${encodeURIComponent(path)}`
      )
      if (!response.ok) {
        throw new Error("Failed to upload icon")
      }
    }
  }

  const isNameDiff = () => title() && title() !== instanceData()?.title
  const isMcVersionDiff = () =>
    mcVersion() && mcVersion() !== instanceData()?.mcVersion
  const isModloaderDiff = () => loader() !== instanceData()?.modloader
  const isModloaderVersionDiff = () =>
    chosenLoaderVersion() !== instanceData()?.modloaderVersion
  const isIconDiff = () => bgPreview() !== instanceData()?.img // not checking for null as it can be unset

  const isUpdatingWithDiffs = () => {
    if (!instanceData()) return true

    return (
      isNameDiff() ||
      isMcVersionDiff() ||
      isModloaderDiff() ||
      isModloaderVersionDiff() ||
      isIconDiff()
    )
  }

  const handleCreate = async () => {
    if (!title()) {
      setError("Fields must be filled in!")
    } else {
      setError("")

      try {
        // Store icon in backend before creating instance
        await storeIconForBackend()

        const instanceId = await createInstanceMutation.mutateAsync({
          group: defaultGroup.data || 1,
          use_loaded_icon: true,
          notes: "",
          name: title()!,
          version: {
            Version: {
              Standard: {
                release: mcVersion() || mappedMcVersions()?.[0]?.id,
                modloaders: loader()
                  ? [
                      {
                        type_: loader()!,
                        version: chosenLoaderVersion() || loaderVersions()[0].id
                      } as ModLoader
                    ]
                  : []
              }
            }
          }
        })

        await prepareInstanceMutation.mutateAsync(instanceId)

        modalsContext?.closeModal()
        navigator.navigate(`/library`)
        toast.success("Instance successfully created.")
      } catch (err) {
        console.error(err)
        modalsContext?.closeModal()
        toast.error("Error while creating the instance.")
      } finally {
        setError("")
        setCustomTitle("")
        setError("")
        setBgPreview(null)
        setMcVersion("")
        setChosenLoaderVersion("")
      }
    }
  }

  const handleUpdate = async () => {
    if (!title()) {
      setError("Fields must be filled in!")
      return
    }

    if (instanceData()?.id) {
      setError("")

      try {
        // Store icon in backend before updating instance
        if (isIconDiff() && iconPath()) {
          await storeIconForBackend()
        }

        await updateInstanceMutation.mutateAsync({
          instance: parseInt(instanceData()!.id, 10),
          useLoadedIcon: isIconDiff() ? { Set: Boolean(bgPreview()) } : null,
          name: isNameDiff() ? { Set: title()! } : null,
          version: isMcVersionDiff()
            ? {
                Set: mcVersion() || mappedMcVersions()?.[0]?.id
              }
            : null,
          modloader:
            isModloaderDiff() || isModloaderVersionDiff()
              ? {
                  Set: loader()
                    ? ({
                        type_: loader()!,
                        version: chosenLoaderVersion() || loaderVersions()[0].id
                      } as ModLoader)
                    : null
                }
              : null
        })

        modalsContext?.closeModal()
        toast.success("Instance successfully updated.")
      } catch (err) {
        console.error(err)
        modalsContext?.closeModal()
        toast.error("Error while creating the instance.")
      } finally {
        setError("")
        setCustomTitle("")
        setError("")
        setBgPreview(null)
        setMcVersion("")
        setChosenLoaderVersion("")
      }
    }
  }

  createEffect(() => {
    if (instanceData()?.modloader === "forge") {
      forgeVersionsQuery.refetch()
    } else if (instanceData()?.modloader === "neoforge") {
      neoForgeVersionsQuery.refetch()
    } else if (instanceData()?.modloader === "fabric") {
      fabricVersionsQuery.refetch()
    } else if (instanceData()?.modloader === "quilt") {
      quiltVersionsQuery.refetch()
    }
  })

  return (
    <div class="flex h-[600px] w-full flex-col">
      <div
        class="flex flex-1 flex-col gap-3 overflow-y-auto p-4"
        style={{ "scrollbar-gutter": "stable" }}
      >
        {/* Instance Details Section */}
        <div class="flex flex-col gap-3">
          <div class="flex w-full items-center">
            <div class="border-t-1 border-lightSlate-400 flex-1 border-solid" />
            <span class="text-lightSlate-400 flex items-center gap-2 px-3 text-base">
              <div class="i-hugeicons:file-02 text-primary-500 text-sm" />
              <Trans key="general:_trn_about" />
            </span>
            <div class="border-t-1 border-lightSlate-400 flex-1 border-solid" />
          </div>
          <div class="flex w-full items-start gap-4">
            <ImagePicker
              imageUrl={bgPreview}
              onSelect={loadPreview}
              onDelete={() => {
                setBgPreview(null)
                setIconPath(null)
              }}
              deletable={true}
              confirmDelete={false}
              sizeClass="h-20 w-20"
              dialogTitle={t("instances:_trn_select_icon")}
              placeholderIcon="i-hugeicons:image-01"
            />
            <div class="flex flex-1 flex-col gap-2">
              <label class="text-lightSlate-400 text-xs font-medium">
                <Trans key="instances:_trn_instance_name" />
              </label>
              <Input
                class="w-full"
                required
                placeholder={t("instances:_trn_new_instance")}
                inputColor="bg-darkSlate-800"
                onInput={(e) => {
                  setCustomTitle(e.currentTarget.value)
                }}
                value={title()!}
                errorMessage={
                  error() && !title()
                    ? t("errors:_trn_error.missing_field_title")
                    : undefined
                }
              />
            </div>
          </div>
        </div>

        {/* Minecraft Version Section */}
        <div class="flex flex-col gap-3">
          <div class="flex w-full items-center">
            <div class="border-t-1 border-lightSlate-400 flex-1 border-solid" />
            <span class="text-lightSlate-400 flex items-center gap-2 px-3 text-base">
              <div class="i-hugeicons:minecraft text-primary-500 text-sm" />
              <Trans key="instances:_trn_instance_mc_version" />
            </span>
            <div class="border-t-1 border-lightSlate-400 flex-1 border-solid" />
          </div>
          <div class="flex w-full flex-col gap-2">
            <Select
              value={mcVersion()}
              onChange={(value) => {
                if (!value) return
                setMcVersion(value)

                if (!loader()) {
                  setLoaderVersions([])
                } else if (isForge()) {
                  const versions = forgeVersionsQuery?.data?.gameVersions.find(
                    (v) => v.id === value
                  )?.loaders
                  setLoaderVersions(versions || [])
                } else if (isNeoForge()) {
                  const versions =
                    neoForgeVersionsQuery?.data?.gameVersions.find(
                      (v) => v.id === value
                    )?.loaders
                  setLoaderVersions(versions || [])
                } else if (isFabric()) {
                  const supported =
                    fabricVersionsQuery?.data?.gameVersions.find(
                      (v) => v.id === value
                    ) ?? false
                  const versions =
                    supported !== false
                      ? fabricVersionsQuery?.data?.gameVersions.find(
                          (v) => v.id === DUMMY_META_VERSION
                        )?.loaders
                      : []
                  setLoaderVersions(versions || [])
                } else if (isQuilt()) {
                  const supported =
                    quiltVersionsQuery?.data?.gameVersions.find(
                      (v) => v.id === value
                    ) ?? false
                  const versions =
                    supported !== false
                      ? quiltVersionsQuery?.data?.gameVersions.find(
                          (v) => v.id === DUMMY_META_VERSION
                        )?.loaders
                      : []
                  setLoaderVersions(versions || [])
                }
              }}
              options={mappedMcVersions().map((v) => v.id)}
              placeholder={t("errors:_trn_error.no_mc_versions")}
              disabled={Boolean(
                ((forgeVersionsQuery.isFetching ||
                  fabricVersionsQuery.isFetching ||
                  quiltVersionsQuery.isFetching ||
                  neoForgeVersionsQuery.isFetching) &&
                  loader()) ||
                  mappedMcVersions().length === 0
              )}
              disallowEmptySelection={true}
              itemComponent={(itemProps) => {
                const version = mappedMcVersions().find(
                  (v) => v.id === itemProps.item.rawValue
                )
                return (
                  <SelectItem item={itemProps.item}>
                    <div class="flex w-full items-center justify-between gap-2">
                      <span
                        classList={{
                          "text-lightSlate-700": Boolean(
                            version && !version.hasModloader && loader()
                          )
                        }}
                      >
                        {itemProps.item.rawValue}
                      </span>
                      <span class="shrink-0">
                        {version &&
                          mapTypeToColor(
                            version.type,
                            Boolean(!version.hasModloader && loader())
                          )}
                      </span>
                    </div>
                  </SelectItem>
                )
              }}
            >
              <SelectTrigger>
                <SelectValue<string>>
                  {(state) => state.selectedOption()}
                </SelectValue>
              </SelectTrigger>
              <SelectContent />
            </Select>
            <div class="flex flex-wrap items-center gap-2">
              <Badge
                variant={snapshotVersionFilter() ? "default" : "secondary"}
                class="cursor-pointer px-2.5 py-1 text-xs"
                onClick={() =>
                  setSnapshotVersionFilter(!snapshotVersionFilter())
                }
                title="Snapshot versions"
              >
                <div class="flex items-center gap-1">
                  <div class="i-hugeicons:test-tube text-xs" />
                  <span>
                    <Trans key="instances:_trn_version_type_snapshot" />
                  </span>
                </div>
              </Badge>
              <Badge
                variant={oldAlphaVersionFilter() ? "default" : "secondary"}
                class="cursor-pointer px-2.5 py-1 text-xs"
                onClick={() =>
                  setOldAlphaVersionFilter(!oldAlphaVersionFilter())
                }
                title="Old alpha versions"
              >
                <div class="flex items-center gap-1">
                  <div class="i-hugeicons:alpha text-xs" />
                  <span>
                    <Trans key="instances:_trn_version_type_alpha" />
                  </span>
                </div>
              </Badge>
              <Badge
                variant={oldBetaVersionFilter() ? "default" : "secondary"}
                class="cursor-pointer px-2.5 py-1 text-xs"
                onClick={() => setOldBetaVersionFilter(!oldBetaVersionFilter())}
                title="Old beta versions"
              >
                <div class="flex items-center gap-1">
                  <div class="i-hugeicons:beta text-xs" />
                  <span>
                    <Trans key="instances:_trn_version_type_beta" />
                  </span>
                </div>
              </Badge>
            </div>
          </div>
        </div>

        {/* Modloader Section */}
        <div class="flex flex-col gap-3">
          <div class="flex w-full items-center">
            <div class="border-t-1 border-lightSlate-400 flex-1 border-solid" />
            <span class="text-lightSlate-400 flex items-center gap-2 px-3 text-base">
              <div class="i-hugeicons:package text-primary-500 text-sm" />
              <Trans key="content:_trn_modloader" />
            </span>
            <div class="border-t-1 border-lightSlate-400 flex-1 border-solid" />
          </div>
          <div class="grid grid-cols-5 gap-3">
            <For each={modloaders}>
              {(modloader) => (
                <button
                  class={`bg-darkSlate-800 hover:outline-darkSlate-600 hover:bg-darkSlate-700 group flex flex-col items-center gap-2 rounded-lg border-0 border-transparent p-3 outline-none ${PRESS_CLASSES}`}
                  classList={{
                    "!outline-primary-500": loader() === modloader.key
                  }}
                  onClick={() => {
                    if (modloader.key === "forge") {
                      forgeVersionsQuery.refetch()
                    } else if (modloader.key === "neoforge") {
                      neoForgeVersionsQuery.refetch()
                    } else if (modloader.key === "fabric") {
                      fabricVersionsQuery.refetch()
                    } else if (modloader.key === "quilt") {
                      quiltVersionsQuery.refetch()
                    }
                    setLoader(!modloader.key ? undefined : modloader.key)
                  }}
                >
                  <img
                    class="h-8 w-8 transition-transform group-hover:scale-110"
                    src={getModloaderIcon(modloader.key || "vanilla")}
                    alt={modloader.label}
                  />
                  <span class="text-lightSlate-300 group-hover:text-lightSlate-50 text-xs font-medium transition-colors">
                    {modloader.label}
                  </span>
                </button>
              )}
            </For>
          </div>

          {/* Modloader Version - Appears inline when modloader selected */}
          <Show when={loader()}>
            <div class="border-primary-500/30 flex flex-col gap-2 border-l-2 pl-4">
              <label class="text-lightSlate-400 text-xs font-medium">
                <Trans key="instances:_trn_instance_loader_version" />
              </label>
              <Switch>
                <Match
                  when={
                    (forgeVersionsQuery.isFetching ||
                      fabricVersionsQuery.isFetching ||
                      quiltVersionsQuery.isFetching ||
                      neoForgeVersionsQuery.isFetching) &&
                    loaderVersions().length === 0
                  }
                >
                  <div class="bg-darkSlate-800 h-10 animate-pulse rounded-md" />
                </Match>
                <Match when={loaderVersions().length > 0}>
                  <Select
                    value={chosenLoaderVersion()}
                    onChange={(value) => value && setChosenLoaderVersion(value)}
                    options={loaderVersions()?.map((v) => v.id) || []}
                    disabled={
                      forgeVersionsQuery.isFetching ||
                      fabricVersionsQuery.isFetching ||
                      quiltVersionsQuery.isFetching ||
                      neoForgeVersionsQuery.isFetching ||
                      !loaderVersions()
                    }
                    disallowEmptySelection={true}
                    itemComponent={(itemProps) => (
                      <SelectItem item={itemProps.item}>
                        {itemProps.item.rawValue}
                      </SelectItem>
                    )}
                  >
                    <SelectTrigger>
                      <SelectValue<string>>
                        {(state) => state.selectedOption()}
                      </SelectValue>
                    </SelectTrigger>
                    <SelectContent />
                  </Select>
                </Match>
                <Match
                  when={
                    loaderVersions().length === 0 &&
                    !forgeVersionsQuery.isFetching &&
                    !fabricVersionsQuery.isFetching &&
                    !quiltVersionsQuery.isFetching &&
                    !neoForgeVersionsQuery.isFetching
                  }
                >
                  <div class="text-lightSlate-500 bg-darkSlate-800 flex items-center gap-2 rounded-md px-3 py-2 text-sm">
                    <div class="i-hugeicons:alert-circle text-yellow-500" />
                    <span>
                      <Trans
                        key="instances:_trn_no_versions_for_mc"
                        options={{ version: mcVersion() }}
                      />
                    </span>
                  </div>
                </Match>
              </Switch>
            </div>
          </Show>
        </div>
      </div>

      {/* Buttons - outside scrollable area */}
      <div class="flex w-full justify-end px-4 pb-4 pt-0">
        <Button
          disabled={Boolean(
            (loaderVersions().length === 0 && loader()) ||
              mappedMcVersions().length === 0 ||
              !isUpdatingWithDiffs()
          )}
          type="primary"
          style={{ width: "100%", "max-width": "200px" }}
          onClick={() => {
            if (instanceData()) handleUpdate()
            else handleCreate()
          }}
        >
          <Switch>
            <Match when={!instanceData()}>
              <div class="flex items-center gap-1.5">
                <div class="i-hugeicons:add-01" />
                <Trans key="instances:_trn_instance_modal_instance_creation_create" />
              </div>
            </Match>
            <Match when={instanceData()}>
              <div class="flex items-center gap-1.5">
                <div class="i-hugeicons:pencil-edit-01" />
                <Trans key="instances:_trn_instance_modal_instance_update" />
              </div>
            </Match>
          </Switch>
        </Button>
      </div>
    </div>
  )
}

export default Custom
