[package]
edition = "2021"
name = "core_module"
version = "0.1.0"

[dependencies]
carbon_app = { path = "../../crates/carbon_app" }

[build-dependencies]
carbon_app = { path = "../../crates/carbon_app" }
