[package]
edition = "2021"
name = "core_module"
version = "0.1.0"
author = "GorillaDevs Inc."

[dependencies]
carbon_app = { path = "../../crates/carbon_app" }

[dev-dependencies]
carbon_app = { path = "../../crates/carbon_app" }

[build-dependencies]
carbon_app = { path = "../../crates/carbon_app" }

[features]
default = []
production = ["carbon_app/production"]
