/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsTagRouteImport } from './routes/components/tag'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsStepsRouteImport } from './routes/components/steps'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'
import { Route as ComponentsSonnerRouteImport } from './routes/components/sonner'
import { Route as ComponentsSliderRouteImport } from './routes/components/slider'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSeparatorRouteImport } from './routes/components/separator'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsRadioRouteImport } from './routes/components/radio'
import { Route as ComponentsProgressRouteImport } from './routes/components/progress'
import { Route as ComponentsPopoverRouteImport } from './routes/components/popover'
import { Route as ComponentsNotificationmanagerRouteImport } from './routes/components/notificationmanager'
import { Route as ComponentsNewsRouteImport } from './routes/components/news'
import { Route as ComponentsMenuRouteImport } from './routes/components/menu'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsDropdownmenuRouteImport } from './routes/components/dropdownmenu'
import { Route as ComponentsDropdownRouteImport } from './routes/components/dropdown'
import { Route as ComponentsCollapsableRouteImport } from './routes/components/collapsable'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/components/textarea',
  path: '/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTagRoute = ComponentsTagRouteImport.update({
  id: '/components/tag',
  path: '/components/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsStepsRoute = ComponentsStepsRouteImport.update({
  id: '/components/steps',
  path: '/components/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/components/spinner',
  path: '/components/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSonnerRoute = ComponentsSonnerRouteImport.update({
  id: '/components/sonner',
  path: '/components/sonner',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSliderRoute = ComponentsSliderRouteImport.update({
  id: '/components/slider',
  path: '/components/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/components/skeleton',
  path: '/components/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSeparatorRoute = ComponentsSeparatorRouteImport.update({
  id: '/components/separator',
  path: '/components/separator',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioRoute = ComponentsRadioRouteImport.update({
  id: '/components/radio',
  path: '/components/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsProgressRoute = ComponentsProgressRouteImport.update({
  id: '/components/progress',
  path: '/components/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPopoverRoute = ComponentsPopoverRouteImport.update({
  id: '/components/popover',
  path: '/components/popover',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNotificationmanagerRoute =
  ComponentsNotificationmanagerRouteImport.update({
    id: '/components/notificationmanager',
    path: '/components/notificationmanager',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsNewsRoute = ComponentsNewsRouteImport.update({
  id: '/components/news',
  path: '/components/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsMenuRoute = ComponentsMenuRouteImport.update({
  id: '/components/menu',
  path: '/components/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDropdownmenuRoute = ComponentsDropdownmenuRouteImport.update({
  id: '/components/dropdownmenu',
  path: '/components/dropdownmenu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDropdownRoute = ComponentsDropdownRouteImport.update({
  id: '/components/dropdown',
  path: '/components/dropdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCollapsableRoute = ComponentsCollapsableRouteImport.update({
  id: '/components/collapsable',
  path: '/components/collapsable',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsable': typeof ComponentsCollapsableRoute
  '/components/dropdown': typeof ComponentsDropdownRoute
  '/components/dropdownmenu': typeof ComponentsDropdownmenuRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/news': typeof ComponentsNewsRoute
  '/components/notificationmanager': typeof ComponentsNotificationmanagerRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/sonner': typeof ComponentsSonnerRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/steps': typeof ComponentsStepsRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tag': typeof ComponentsTagRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsable': typeof ComponentsCollapsableRoute
  '/components/dropdown': typeof ComponentsDropdownRoute
  '/components/dropdownmenu': typeof ComponentsDropdownmenuRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/news': typeof ComponentsNewsRoute
  '/components/notificationmanager': typeof ComponentsNotificationmanagerRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/sonner': typeof ComponentsSonnerRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/steps': typeof ComponentsStepsRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tag': typeof ComponentsTagRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsable': typeof ComponentsCollapsableRoute
  '/components/dropdown': typeof ComponentsDropdownRoute
  '/components/dropdownmenu': typeof ComponentsDropdownmenuRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/news': typeof ComponentsNewsRoute
  '/components/notificationmanager': typeof ComponentsNotificationmanagerRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/sonner': typeof ComponentsSonnerRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/steps': typeof ComponentsStepsRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/tag': typeof ComponentsTagRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/checkbox'
    | '/components/collapsable'
    | '/components/dropdown'
    | '/components/dropdownmenu'
    | '/components/input'
    | '/components/menu'
    | '/components/news'
    | '/components/notificationmanager'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/sonner'
    | '/components/spinner'
    | '/components/steps'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tag'
    | '/components/textarea'
    | '/components/tooltip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/checkbox'
    | '/components/collapsable'
    | '/components/dropdown'
    | '/components/dropdownmenu'
    | '/components/input'
    | '/components/menu'
    | '/components/news'
    | '/components/notificationmanager'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/sonner'
    | '/components/spinner'
    | '/components/steps'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tag'
    | '/components/textarea'
    | '/components/tooltip'
  id:
    | '__root__'
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/checkbox'
    | '/components/collapsable'
    | '/components/dropdown'
    | '/components/dropdownmenu'
    | '/components/input'
    | '/components/menu'
    | '/components/news'
    | '/components/notificationmanager'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio'
    | '/components/select'
    | '/components/separator'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/sonner'
    | '/components/spinner'
    | '/components/steps'
    | '/components/switch'
    | '/components/tabs'
    | '/components/tag'
    | '/components/textarea'
    | '/components/tooltip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsCollapsableRoute: typeof ComponentsCollapsableRoute
  ComponentsDropdownRoute: typeof ComponentsDropdownRoute
  ComponentsDropdownmenuRoute: typeof ComponentsDropdownmenuRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsMenuRoute: typeof ComponentsMenuRoute
  ComponentsNewsRoute: typeof ComponentsNewsRoute
  ComponentsNotificationmanagerRoute: typeof ComponentsNotificationmanagerRoute
  ComponentsPopoverRoute: typeof ComponentsPopoverRoute
  ComponentsProgressRoute: typeof ComponentsProgressRoute
  ComponentsRadioRoute: typeof ComponentsRadioRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSeparatorRoute: typeof ComponentsSeparatorRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSliderRoute: typeof ComponentsSliderRoute
  ComponentsSonnerRoute: typeof ComponentsSonnerRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsStepsRoute: typeof ComponentsStepsRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTagRoute: typeof ComponentsTagRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/components/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tag': {
      id: '/components/tag'
      path: '/components/tag'
      fullPath: '/components/tag'
      preLoaderRoute: typeof ComponentsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/components/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/steps': {
      id: '/components/steps'
      path: '/components/steps'
      fullPath: '/components/steps'
      preLoaderRoute: typeof ComponentsStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/components/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sonner': {
      id: '/components/sonner'
      path: '/components/sonner'
      fullPath: '/components/sonner'
      preLoaderRoute: typeof ComponentsSonnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/components/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/components/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/separator': {
      id: '/components/separator'
      path: '/components/separator'
      fullPath: '/components/separator'
      preLoaderRoute: typeof ComponentsSeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio': {
      id: '/components/radio'
      path: '/components/radio'
      fullPath: '/components/radio'
      preLoaderRoute: typeof ComponentsRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/components/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/popover': {
      id: '/components/popover'
      path: '/components/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/notificationmanager': {
      id: '/components/notificationmanager'
      path: '/components/notificationmanager'
      fullPath: '/components/notificationmanager'
      preLoaderRoute: typeof ComponentsNotificationmanagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/news': {
      id: '/components/news'
      path: '/components/news'
      fullPath: '/components/news'
      preLoaderRoute: typeof ComponentsNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/components/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dropdownmenu': {
      id: '/components/dropdownmenu'
      path: '/components/dropdownmenu'
      fullPath: '/components/dropdownmenu'
      preLoaderRoute: typeof ComponentsDropdownmenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dropdown': {
      id: '/components/dropdown'
      path: '/components/dropdown'
      fullPath: '/components/dropdown'
      preLoaderRoute: typeof ComponentsDropdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/collapsable': {
      id: '/components/collapsable'
      path: '/components/collapsable'
      fullPath: '/components/collapsable'
      preLoaderRoute: typeof ComponentsCollapsableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsCollapsableRoute: ComponentsCollapsableRoute,
  ComponentsDropdownRoute: ComponentsDropdownRoute,
  ComponentsDropdownmenuRoute: ComponentsDropdownmenuRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsMenuRoute: ComponentsMenuRoute,
  ComponentsNewsRoute: ComponentsNewsRoute,
  ComponentsNotificationmanagerRoute: ComponentsNotificationmanagerRoute,
  ComponentsPopoverRoute: ComponentsPopoverRoute,
  ComponentsProgressRoute: ComponentsProgressRoute,
  ComponentsRadioRoute: ComponentsRadioRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSeparatorRoute: ComponentsSeparatorRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSliderRoute: ComponentsSliderRoute,
  ComponentsSonnerRoute: ComponentsSonnerRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsStepsRoute: ComponentsStepsRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTagRoute: ComponentsTagRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
