// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.
export type Procedures = { queries: { key: "echo", input: string, result: string } | { key: "java.getAvailableJavas", input: null, result: Java }, mutations: never, subscriptions: { key: "invalidateQuery", input: null, result: null } }

export type Java = { name: string, path: string }
