// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.
export type Procedures = { queries: { key: "app.getTheme", input: null, result: number } | { key: "echo", input: string, result: string } | { key: "java.autoSetupjavaProgress", input: null, result: number } | { key: "java.getAvailableJavas", input: null, result: { [key: number]: Java } } | { key: "mc.getInstance", input: string, result: { id: string, name: string } } | { key: "mc.getInstances", input: null, result: Instance[] }, mutations: { key: "app.setTheme", input: string, result: null } | { key: "java.autoSetupJava", input: { major_version: number, type: AutoSetupTypes }, result: null } | { key: "java.deleteAutoSetupJava", input: number, result: null } | { key: "java.setDefaultJava", input: { major_version: number, id: string }, result: null } | { key: "mc.updateInstanceName", input: { id: string, new_name: string }, result: null }, subscriptions: { key: "invalidateQuery", input: null, result: string } }

export type AutoSetupTypes = "AdoptOpenJDK" | "MojangJDK"

export type Instance = { id: string, name: string }

export type Java = { default_id: string, java: JavaDetails[] }

export type JavaDetails = { id: string, version: string, path: string, type: JavaType }

export type JavaType = "Local" | "AutoSetup"
