[package]
edition = "2021"
name = "native_interface"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { workspace = true, features = ["ws"] }
directories = { workspace = true }
# dotenv = { workspace = true }
napi = { workspace = true, features = ["napi8"] }
# napi-derive = { workspace = true, features = ["type-def"] }
rspc = { workspace = true, features = ["axum"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "json"] }
tower-http = { workspace = true, default-features = false, features = ["cors"] }
carbon_app = { path = "../../crates/carbon_app" }

[build-dependencies]
napi-build = "2.0.1"
rspc = { workspace = true, features = ["axum"] }
carbon_app = { path = "../../crates/carbon_app" }
tokio = { workspace = true }


[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"
