[package]
edition = "2021"
name = "core"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.6.2", features = ["ws"] }
directories = "4.0.1"
dotenv = "0.15.0"
napi = { version = "2.10.4", features = ["napi8"] }
napi-derive = { version = "2.9.3", features = ["type-def"] }
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "7e6d9e84a0a343b3dd3cbca3ce326b58deeb3a46", features=["axum"] }
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
tower-http = { version = "0.3.4", default-features = false, features = ["cors"] }
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
carbon_app = { path = "../../crates/carbon_app" }
carbon_domain = { path = "../../crates/carbon_domain" }

[build-dependencies]
napi-build = "2.0.1"
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "7e6d9e84a0a343b3dd3cbca3ce326b58deeb3a46", features=["axum"] }
carbon_app = { path = "../../crates/carbon_app" }
tokio = { version = "1.22.0", features = ["full"] }


[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"