name: Docker x64 Desktop Build

on: push

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  docker_x64:
    defaults:
      run:
        working-directory: ./GDLauncher
    if: github.event_name == 'push' && !contains(github.ref, 'refs/heads/develop') && !contains(github.ref, 'refs/heads/release') && !contains(github.ref, 'refs/heads/upstream') && !contains(github.event.head_commit.message, '[RUN_ALL_CI_CHECKS]')
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          path: GDLauncher
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.70.0
          targets: x86_64-unknown-linux-gnu
          components: clippy, rustfmt
      - name: Prepare
        run: |
          echo "" > crates/carbon_app/src/db.rs
          cargo fmt --check
      - run: |
          npm run sudo-init
          chmod -R a+x node_modules
      - name: Iridium patchfix
        run: node iridium_patchfix.js
      - name: Prisma codegen
        env:
          CARGO_INCREMENTAL: 0
        run: pnpm prisma:generate:linux-x64
      - name: Build
        run: pnpm build:linux-x64
        env:
          CARGO_INCREMENTAL: 0
          BASE_API: ${{ vars.BASE_API }}
          MS_AUTH_CLIENT_ID: ${{ vars.MS_AUTH_CLIENT_ID }}
      - name: Lint
        run: pnpm lint
      - name: Clear target before tests to avoid folder getting too big
        shell: bash
        run: rm -rf target
      - name: Test
        env:
          CARGO_INCREMENTAL: 0
          BASE_API: ${{ vars.BASE_API }}
          MS_AUTH_CLIENT_ID: ${{ vars.MS_AUTH_CLIENT_ID }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm test
