name: MacOS ARM64 Desktop Build

on: push

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  mac_arm64:
    defaults:
      run:
        working-directory: ./GDLauncher
    if: contains(github.ref, 'refs/heads/develop') || contains(github.ref, 'refs/heads/release') || (github.event_name == 'push' && !contains(github.ref, 'refs/heads/develop') && !contains(github.ref, 'refs/heads/release') && contains(github.event.head_commit.message, '[RUN_ALL_CI_CHECKS]'))
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          path: GDLauncher
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.68.2
          targets: aarch64-apple-darwin
          components: clippy, rustfmt
      - name: Prepare
        run: |
          echo "" > crates/carbon_app/src/db.rs
          cargo fmt --check
      - run: |
          npm run sudo-init
          chmod -R a+x node_modules
      - name: Codegen
        env:
          CARGO_INCREMENTAL: 0
        run: pnpm codegen
      - name: Build
        run: pnpm build:mac-arm64
        env:
          CARGO_INCREMENTAL: 0
      # - name: Lint
      #   run: pnpm lint
      - name: Clear target before tests to avoid folder getting too big
        shell: bash
        run: rm -rf target
      - name: Test
        env:
          CARGO_INCREMENTAL: 0
        run: pnpm test
