name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Init submodule if available
      env: 
        is_token: ${{ secrets.MACHINE_USER_TOKEN }}
      if: ${{ env.is_token != '' }}
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
          git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Prepare
      run: |
          echo "" > crates/carbon_app/src/db.rs
          cargo fmt --check
    - run: |
        npm run sudo-init
        chmod -R a+x node_modules
    - name: Codegen
      run: pnpm codegen
    - name: Build
      run: IS_DOCKER_TEST=true pnpm build:linux-x64
    - name: Lint
      run: pnpm lint
    - name: Test
      run: pnpm test -- --features production -- --include-ignored
