name: Ubuntu x64 Desktop Build

on: push

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ubuntu_x64:
    defaults:
      run:
        working-directory: ./GDLauncher
    if: contains(github.ref, 'refs/heads/develop') || contains(github.ref, 'refs/heads/release') || (github.event_name == 'push' && !contains(github.ref, 'refs/heads/develop') && !contains(github.ref, 'refs/heads/release') && contains(github.event.head_commit.message, '[RUN_ALL_CI_CHECKS]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: GDLauncher
      - uses: actions/checkout@v3
        env:
          is_token: ${{ secrets.MACHINE_USER_TOKEN }}
        if: ${{ env.is_token != '' }}
        with:
          repository: gorilla-devs/iridium
          ref: release
          ssh-key: ${{ secrets.MACHINE_USER_TOKEN }}
          path: GDLauncher/crates/iridium
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update rust
        run: |
          rustup update
          rustup target add x86_64-unknown-linux-gnu
          rustup default x86_64-unknown-linux-gnu
      - name: Prepare
        run: |
          echo "" > crates/carbon_app/src/db.rs
          cargo fmt --check
      - run: |
          npm run sudo-init
          chmod -R a+x node_modules
      - name: Codegen
        env:
          CARGO_INCREMENTAL: 0
        run: pnpm codegen
      - name: Build
        run: pnpm build:linux-x64
        env:
          CORE_MODULE_DSN: ${{ secrets.CORE_MODULE_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_MAIN_DSN: ${{ secrets.VITE_MAIN_DSN }}
          CARGO_INCREMENTAL: 0
      - name: Lint
        run: pnpm lint
      - name: Clear target before tests to avoid folder getting too big
        shell: bash
        run: rm -rf target
      - name: Test
        env:
          CORE_MODULE_DSN: ${{ secrets.CORE_MODULE_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_MAIN_DSN: ${{ secrets.VITE_MAIN_DSN }}
          CARGO_INCREMENTAL: 0
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm test -- --features production -- --include-ignored
